import type { DestinationEntry } from '../types'

// 国内35エリア。
// 各 spot は 観光/グルメ/その他 のいずれか。テーマコード（th）で variant 展開対象が決まる。
// pop 1-5: 5 が最重要スポット（必ず採用候補に来る）

export const DOMESTIC_PART1: DestinationEntry[] = [
    // ========================================
    // 1. 京都
    // ========================================
    {
        id: 'kyoto', name: '京都', country: '日本', region: 'kansai',
        trip_style: 'public_transit', intra_mode: '電車', intra_gap_min: 30,
        themes: ['sg', 'gm', 'hs', 'cp', 'wh', 'np'],
        areas: [
            { id: 'higashiyama', name: '東山' },
            { id: 'arashiyama', name: '嵐山' },
            { id: 'gion', name: '祇園' },
            { id: 'kinkaku', name: '金閣寺周辺' },
            { id: 'fushimi', name: '伏見' },
            { id: 'kyoto-sta', name: '京都駅周辺' },
        ],
        spots: [
            { n: '清水寺', d: '京都を代表する寺院。舞台からの眺望と桜・紅葉が名物', t: '観光', dur: 90, addr: '京都市東山区清水', area: 'higashiyama', th: ['sg', 'hs', 'wh'], pop: 5 },
            { n: '伏見稲荷大社', d: '千本鳥居が連なる稲荷総本宮。早朝参拝が人気', t: '観光', dur: 120, addr: '京都市伏見区深草', area: 'fushimi', th: ['sg', 'hs', 'np'], pop: 5, morningOk: true },
            { n: '金閣寺', d: '黄金色の舎利殿が鏡湖池に映る世界遺産', t: '観光', dur: 60, addr: '京都市北区金閣寺町', area: 'kinkaku', th: ['sg', 'hs', 'wh'], pop: 5 },
            { n: '銀閣寺', d: '東山文化を代表するわびさびの世界遺産', t: '観光', dur: 60, addr: '京都市左京区銀閣寺町', area: 'higashiyama', th: ['sg', 'hs', 'wh'], pop: 4 },
            { n: '嵐山・渡月橋', d: '桂川に架かる名橋と嵐山の自然', t: '観光', dur: 60, addr: '京都市右京区嵯峨', area: 'arashiyama', th: ['sg', 'np', 'cp'], pop: 5 },
            { n: '竹林の小径', d: '嵐山の竹に囲まれた幻想的な散策路', t: '観光', dur: 45, addr: '京都市右京区嵯峨', area: 'arashiyama', th: ['sg', 'np', 'cp'], pop: 5 },
            { n: '天龍寺', d: '世界遺産の禅寺。曹源池庭園が見事', t: '観光', dur: 75, addr: '京都市右京区嵯峨', area: 'arashiyama', th: ['sg', 'hs', 'wh'], pop: 4 },
            { n: '祇園・花見小路', d: '京都らしい石畳の街並み。お茶屋が並ぶ', t: '観光', dur: 60, addr: '京都市東山区祇園', area: 'gion', th: ['sg', 'hs', 'cp'], pop: 5 },
            { n: '八坂神社', d: '祇園祭で知られる縁結びの社', t: '観光', dur: 45, addr: '京都市東山区祇園町', area: 'gion', th: ['sg', 'hs'], pop: 4 },
            { n: '南禅寺', d: '臨済宗大本山と水路閣のレンガ造り', t: '観光', dur: 75, addr: '京都市左京区南禅寺', area: 'higashiyama', th: ['sg', 'hs', 'wh'], pop: 4 },
            { n: '二条城', d: '徳川将軍家の世界遺産。大政奉還の舞台', t: '観光', dur: 90, addr: '京都市中京区二条通堀川', area: 'kyoto-sta', th: ['sg', 'hs', 'wh'], pop: 4 },
            { n: '京都鉄道博物館', d: 'SLから新幹線まで、家族で楽しめる', t: '観光', dur: 150, addr: '京都市下京区観喜寺町', area: 'kyoto-sta', th: ['sg', 'fm'], pop: 3 },
            { n: '錦市場', d: '京の台所と呼ばれるグルメ商店街', t: 'グルメ', dur: 75, addr: '京都市中京区錦小路', area: 'gion', th: ['gm', 'sg'], pop: 5 },
            { n: '一保堂茶舗 喫茶室嘉木', d: '本格抹茶を楽しめる老舗茶舗の喫茶室', t: 'グルメ', dur: 60, addr: '京都市中京区寺町通二条上ル', area: 'gion', th: ['gm', 'hs'], pop: 4 },
            { n: '%ARABICA Kyoto 嵐山', d: '渡月橋を望むスタイリッシュなコーヒー', t: 'グルメ', dur: 45, addr: '京都市右京区嵯峨天龍寺', area: 'arashiyama', th: ['gm', 'cp'], pop: 4 },
            { n: '権太呂 本店', d: '京の老舗うどん。にしんそばが名物', t: 'グルメ', dur: 60, addr: '京都市中京区麩屋町', area: 'gion', th: ['gm', 'hs'], pop: 4 },
            { n: '京都祇園 天ぷら八坂圓堂', d: 'ミシュラン掲載の本格天ぷら', t: 'グルメ', dur: 90, addr: '京都市東山区八坂上町', area: 'gion', th: ['gm', 'cp'], pop: 4, bk: true },
            { n: '中村藤吉本店', d: '宇治の老舗茶舗の抹茶パフェ', t: 'グルメ', dur: 60, addr: '宇治市宇治壱番', area: 'fushimi', th: ['gm', 'hs'], pop: 5 },
            { n: '京都国立博物館', d: '日本美術の名品を多数収蔵', t: '観光', dur: 90, addr: '京都市東山区茶屋町', area: 'higashiyama', th: ['sg', 'ar', 'hs'], pop: 3 },
            { n: '北野天満宮', d: '学問の神様、菅原道真公を祀る', t: '観光', dur: 45, addr: '京都市上京区馬喰町', area: 'kinkaku', th: ['sg', 'hs'], pop: 3 },
            { n: '龍安寺', d: '石庭で世界的に有名な世界遺産', t: '観光', dur: 60, addr: '京都市右京区龍安寺', area: 'kinkaku', th: ['sg', 'hs', 'wh'], pop: 4 },
            { n: '京都駅ビル空中経路', d: '京都駅の建築美と京都市内の眺望', t: '観光', dur: 30, addr: '京都市下京区東塩小路', area: 'kyoto-sta', th: ['sg', 'np'], pop: 3 },
            { n: '東寺', d: '五重塔のある世界遺産。京都駅近く', t: '観光', dur: 60, addr: '京都市南区九条町', area: 'kyoto-sta', th: ['sg', 'hs', 'wh'], pop: 4 },
            { n: '哲学の道', d: '銀閣寺から南禅寺へ至る桜の名所', t: '観光', dur: 45, addr: '京都市左京区', area: 'higashiyama', th: ['sg', 'np', 'cp'], pop: 4 },
            { n: '貴船神社', d: '川床と縁結びで知られる古社', t: '観光', dur: 60, addr: '京都市左京区鞍馬貴船町', area: 'higashiyama', th: ['sg', 'cp', 'hs'], pop: 3 },
        ],
        hotels: [
            { n: 'ザ・リッツ・カールトン京都', addr: '京都市中京区鴨川二条大橋畔', area: 'gion', price: 95000 },
            { n: 'ホテル京阪 京都グランデ', addr: '京都市下京区東塩小路', area: 'kyoto-sta', price: 22000 },
            { n: '京都祇園 ホテル ザ・セレスティン', addr: '京都市東山区八坂通東大路', area: 'gion', price: 36000 },
            { n: '都ホテル京都八坂', addr: '京都市東山区粟田口三条坊町', area: 'gion', price: 28000 },
            { n: '京都駅前 ホテルグランヴィア京都', addr: '京都市下京区烏丸通塩小路', area: 'kyoto-sta', price: 25000 },
        ],
        titleHints: {
            sg: ['王道観光', '名所巡り'],
            gm: ['京グルメ満喫', '京料理を味わう'],
            hs: ['古都歴史散策', '世界遺産巡り'],
            cp: ['祇園で過ごす', '抹茶とロマンチック'],
            wh: ['世界遺産を巡る'],
        },
    },

    // ========================================
    // 2. 沖縄本島
    // ========================================
    {
        id: 'okinawa-main', name: '沖縄', titleAlias: '沖縄本島', country: '日本', region: 'okinawa_main',
        trip_style: 'rental_car', intra_mode: 'レンタカー', intra_gap_min: 45,
        themes: ['sg', 'gm', 'np', 'bc', 'fm', 'cp'],
        areas: [
            { id: 'naha', name: '那覇市内' },
            { id: 'churaumi', name: '美ら海・本部' },
            { id: 'nanjo', name: '南城・知念' },
            { id: 'onna', name: '恩納村' },
            { id: 'yomitan', name: '読谷' },
        ],
        spots: [
            { n: '美ら海水族館', d: '世界最大級のジンベエザメに会える', t: '観光', dur: 180, addr: '本部町石川', area: 'churaumi', th: ['sg', 'fm', 'np'], pop: 5 },
            { n: '古宇利大橋', d: '海の上を走る2kmの絶景ドライブロード', t: '観光', dur: 60, addr: '今帰仁村古宇利', area: 'churaumi', th: ['sg', 'np', 'cp'], pop: 5 },
            { n: '古宇利オーシャンタワー', d: '古宇利島の海を360度見渡せる展望台', t: '観光', dur: 60, addr: '今帰仁村古宇利', area: 'churaumi', th: ['sg', 'np', 'cp'], pop: 4 },
            { n: '万座毛', d: '象の鼻のような奇岩と東シナ海の絶壁', t: '観光', dur: 45, addr: '恩納村恩納', area: 'onna', th: ['sg', 'np'], pop: 5 },
            { n: '青の洞窟', d: '真栄田岬のシュノーケル名所', t: '観光', dur: 120, addr: '恩納村真栄田', area: 'onna', th: ['ex', 'np', 'bc'], pop: 5, bk: true },
            { n: '首里城公園', d: '琉球王国の世界遺産。守礼門と城郭', t: '観光', dur: 90, addr: '那覇市首里金城町', area: 'naha', th: ['sg', 'hs', 'wh'], pop: 5 },
            { n: '国際通り', d: '那覇のメインストリート。土産物店が並ぶ', t: '観光', dur: 90, addr: '那覇市牧志', area: 'naha', th: ['sg', 'sp'], pop: 5 },
            { n: '第一牧志公設市場', d: '沖縄の食材と郷土料理の聖地', t: 'グルメ', dur: 75, addr: '那覇市松尾', area: 'naha', th: ['gm', 'sg'], pop: 4 },
            { n: '斎場御嶽', d: '琉球王国最高の聖地（世界遺産）', t: '観光', dur: 60, addr: '南城市知念', area: 'nanjo', th: ['sg', 'hs', 'wh'], pop: 4 },
            { n: '知念岬公園', d: 'コバルトブルーの太平洋を望む岬', t: '観光', dur: 45, addr: '南城市知念', area: 'nanjo', th: ['sg', 'np', 'cp'], pop: 4 },
            { n: 'ニライカナイ橋', d: '南城市の絶景ドライブスポット', t: '観光', dur: 30, addr: '南城市知念', area: 'nanjo', th: ['sg', 'np'], pop: 3 },
            { n: '残波岬', d: '読谷の断崖と灯台。サンセットの名所', t: '観光', dur: 45, addr: '読谷村宇座', area: 'yomitan', th: ['sg', 'np', 'cp'], pop: 4 },
            { n: 'やちむんの里', d: '読谷の陶芸の里。器の街歩き', t: '観光', dur: 90, addr: '読谷村座喜味', area: 'yomitan', th: ['sg', 'ar'], pop: 3 },
            { n: '瀬長島ウミカジテラス', d: '空港から近い海カフェの集積地', t: 'グルメ', dur: 90, addr: '豊見城市瀬長', area: 'naha', th: ['gm', 'cp', 'np'], pop: 4 },
            { n: 'ステーキハウス88 国際通り店', d: '夜遅くまで開く沖縄ステーキの定番', t: 'グルメ', dur: 60, addr: '那覇市牧志', area: 'naha', th: ['gm'], pop: 3, eveningOk: true },
            { n: 'お食事処 三笠', d: '那覇で愛される沖縄そばの老舗', t: 'グルメ', dur: 45, addr: '那覇市松山', area: 'naha', th: ['gm'], pop: 4 },
            { n: 'カフェこくう', d: '南城の絶景畑カフェ。八重瀬の海を望む', t: 'グルメ', dur: 75, addr: '南城市佐敷', area: 'nanjo', th: ['gm', 'cp', 'np'], pop: 4 },
            { n: 'ブセナ海中公園', d: '海中展望塔とグラスボートで珊瑚観察', t: '観光', dur: 90, addr: '名護市喜瀬', area: 'churaumi', th: ['sg', 'fm', 'np'], pop: 3 },
            { n: 'ナゴパイナップルパーク', d: '家族で楽しめるパイナップル園', t: '観光', dur: 75, addr: '名護市為又', area: 'churaumi', th: ['sg', 'fm'], pop: 3 },
            { n: 'OKINAWAフルーツらんど', d: '南国フルーツを学べるテーマパーク', t: '観光', dur: 75, addr: '名護市為又', area: 'churaumi', th: ['sg', 'fm'], pop: 3 },
            { n: 'おきなわワールド', d: '玉泉洞・エイサーショー・琉球文化体験', t: '観光', dur: 150, addr: '南城市玉城', area: 'nanjo', th: ['sg', 'fm', 'hs'], pop: 4 },
            { n: 'ガンガラーの谷', d: '太古の鍾乳洞跡を歩くツアー', t: '観光', dur: 90, addr: '南城市玉城', area: 'nanjo', th: ['ex', 'np'], pop: 4, bk: true },
            { n: '備瀬のフクギ並木', d: '美ら海近くの集落のフクギトンネル', t: '観光', dur: 60, addr: '本部町備瀬', area: 'churaumi', th: ['sg', 'np', 'cp'], pop: 4 },
            { n: 'やんばる国立公園', d: '世界自然遺産の亜熱帯の森', t: '観光', dur: 120, addr: '国頭村', area: 'churaumi', th: ['sg', 'nt', 'wh'], pop: 3 },
            { n: '塩屋湾の夕日', d: '大宜味村の絶景サンセットスポット', t: '観光', dur: 30, addr: '大宜味村塩屋', area: 'churaumi', th: ['sg', 'np', 'cp'], pop: 3 },
        ],
        hotels: [
            { n: 'ハレクラニ沖縄', addr: '恩納村名嘉真', area: 'onna', price: 95000 },
            { n: 'ハイアットリージェンシー瀬良垣アイランド沖縄', addr: '恩納村瀬良垣', area: 'onna', price: 72000 },
            { n: 'ザ・ブセナテラス', addr: '名護市喜瀬', area: 'churaumi', price: 65000 },
            { n: 'ホテルJALシティ那覇', addr: '那覇市牧志', area: 'naha', price: 18000 },
            { n: 'ザ・テラスクラブ アット ブセナ', addr: '名護市喜瀬', area: 'churaumi', price: 58000 },
            { n: 'ANAインターコンチネンタル万座ビーチリゾート', addr: '恩納村瀬良垣', area: 'onna', price: 48000 },
        ],
        titleHints: {
            bc: ['離島ビーチ満喫', '海を満喫'],
            np: ['絶景ドライブ', '南国の絶景'],
            fm: ['家族で楽しむ沖縄', 'こども大満足'],
            cp: ['南国カップル旅'],
        },
    },

    // ========================================
    // 3. 札幌・小樽
    // ========================================
    {
        id: 'sapporo-otaru', name: '札幌', titleAlias: '札幌・小樽', country: '日本', region: 'hokkaido',
        trip_style: 'public_transit', intra_mode: '電車', intra_gap_min: 30,
        themes: ['sg', 'gm', 'np', 'cp', 'fm'],
        areas: [
            { id: 'sapporo-c', name: '札幌中心部' },
            { id: 'otaru', name: '小樽' },
            { id: 'jozankei', name: '定山渓' },
            { id: 'moiwa', name: '藻岩山' },
        ],
        spots: [
            { n: '札幌時計台', d: '札幌のシンボル。明治時代の演武場', t: '観光', dur: 30, addr: '札幌市中央区北一条西', area: 'sapporo-c', th: ['sg', 'hs'], pop: 4 },
            { n: '大通公園', d: '札幌の中心を貫く緑の広場', t: '観光', dur: 60, addr: '札幌市中央区大通西', area: 'sapporo-c', th: ['sg', 'cp'], pop: 4 },
            { n: 'さっぽろテレビ塔', d: '大通公園を一望できる展望塔', t: '観光', dur: 45, addr: '札幌市中央区大通西', area: 'sapporo-c', th: ['sg', 'np'], pop: 3 },
            { n: '藻岩山ロープウェイ', d: '北海道三大夜景に選ばれる絶景', t: '観光', dur: 90, addr: '札幌市中央区伏見', area: 'moiwa', th: ['np', 'cp', 'ng'], pop: 5 },
            { n: '北海道庁旧本庁舎', d: 'レンガ造りのレトロ建築（赤れんが庁舎）', t: '観光', dur: 45, addr: '札幌市中央区北三条西', area: 'sapporo-c', th: ['sg', 'hs'], pop: 4 },
            { n: '白い恋人パーク', d: 'お土産の名店が運営する菓子工場テーマパーク', t: '観光', dur: 120, addr: '札幌市西区宮の沢', area: 'sapporo-c', th: ['sg', 'fm', 'gm'], pop: 4 },
            { n: '札幌市円山動物園', d: '家族で楽しめる動物園', t: '観光', dur: 120, addr: '札幌市中央区宮ケ丘', area: 'sapporo-c', th: ['sg', 'fm'], pop: 3 },
            { n: '小樽運河', d: '夕暮れと夜景が美しいレトロ運河', t: '観光', dur: 75, addr: '小樽市色内', area: 'otaru', th: ['sg', 'np', 'cp', 'hs'], pop: 5 },
            { n: '小樽オルゴール堂 本館', d: 'メルヘン交差点のオルゴール専門館', t: '観光', dur: 45, addr: '小樽市住吉町', area: 'otaru', th: ['sg', 'cp'], pop: 4 },
            { n: '北一硝子三号館', d: '小樽ガラスの代表的なギャラリー', t: '観光', dur: 60, addr: '小樽市堺町', area: 'otaru', th: ['sg', 'ar'], pop: 4 },
            { n: 'ルタオ本店', d: 'ドゥーブルフロマージュで有名なチーズスイーツ', t: 'グルメ', dur: 45, addr: '小樽市堺町', area: 'otaru', th: ['gm', 'cp'], pop: 5 },
            { n: '味の三平', d: '味噌ラーメン発祥の地と言われる老舗', t: 'グルメ', dur: 45, addr: '札幌市中央区南一条西', area: 'sapporo-c', th: ['gm'], pop: 4 },
            { n: 'すみれ 札幌本店', d: '濃厚味噌ラーメンの代表格', t: 'グルメ', dur: 45, addr: '札幌市豊平区中の島', area: 'sapporo-c', th: ['gm'], pop: 4 },
            { n: 'スープカレー GARAKU', d: '札幌スープカレーの行列店', t: 'グルメ', dur: 60, addr: '札幌市中央区南二条西', area: 'sapporo-c', th: ['gm'], pop: 5 },
            { n: 'サッポロビール園', d: 'ジンギスカン食べ放題と園内ガイド', t: 'グルメ', dur: 90, addr: '札幌市東区北七条東', area: 'sapporo-c', th: ['gm', 'fm'], pop: 4 },
            { n: 'すすきの', d: '北日本最大級の歓楽街・夜のグルメ', t: 'グルメ', dur: 120, addr: '札幌市中央区南四条西', area: 'sapporo-c', th: ['gm', 'ng'], pop: 5, eveningOk: true },
            { n: '二条市場', d: '札幌の朝市。海鮮丼の名店多数', t: 'グルメ', dur: 60, addr: '札幌市中央区南三条東', area: 'sapporo-c', th: ['gm', 'sg'], pop: 4, morningOk: true },
            { n: '小樽寿司屋通り', d: '小樽ガラス通りに近い寿司の名店通り', t: 'グルメ', dur: 90, addr: '小樽市花園', area: 'otaru', th: ['gm'], pop: 5 },
            { n: '定山渓温泉街散策', d: '札幌から1時間の名湯', t: '観光', dur: 120, addr: '札幌市南区定山渓温泉', area: 'jozankei', th: ['on', 'np'], pop: 4 },
            { n: '豊平峡ダム', d: '紅葉の名所と電気バスでアクセス', t: '観光', dur: 90, addr: '札幌市南区定山渓', area: 'jozankei', th: ['np', 'sg'], pop: 3 },
            { n: 'モエレ沼公園', d: 'イサム・ノグチ設計の大型公園', t: '観光', dur: 120, addr: '札幌市東区モエレ沼公園', area: 'sapporo-c', th: ['sg', 'ar', 'fm'], pop: 4 },
            { n: '北海道神宮', d: '札幌の総鎮守。初詣や桜の名所', t: '観光', dur: 60, addr: '札幌市中央区宮ケ丘', area: 'sapporo-c', th: ['sg', 'hs'], pop: 3 },
            { n: 'JRタワー展望室T38', d: '札幌駅直結の高層展望', t: '観光', dur: 45, addr: '札幌市中央区北五条西', area: 'sapporo-c', th: ['sg', 'np', 'ng'], pop: 3 },
        ],
        hotels: [
            { n: 'JRタワーホテル日航札幌', addr: '札幌市中央区北五条西', area: 'sapporo-c', price: 32000 },
            { n: 'ホテルオークラ札幌', addr: '札幌市中央区南一条西', area: 'sapporo-c', price: 26000 },
            { n: '小樽朝里クラッセホテル', addr: '小樽市朝里川温泉', area: 'otaru', price: 18000 },
            { n: '札幌グランドホテル', addr: '札幌市中央区北一条西', area: 'sapporo-c', price: 28000 },
            { n: '定山渓万世閣ホテルミリオーネ', addr: '札幌市南区定山渓温泉東', area: 'jozankei', price: 24000 },
        ],
        titleHints: {
            sg: ['札幌・小樽王道', '北海道の玄関口'],
            gm: ['北海道グルメ', 'スープカレーと味噌ラーメン'],
            np: ['夜景と運河'],
        },
    },

    // ========================================
    // 4. 東京
    // ========================================
    {
        id: 'tokyo', name: '東京', country: '日本', region: 'kanto',
        trip_style: 'public_transit', intra_mode: '電車', intra_gap_min: 30,
        themes: ['sg', 'gm', 'sp', 'cp', 'fm', 'ar', 'ng'],
        areas: [
            { id: 'asakusa', name: '浅草' },
            { id: 'shinjuku', name: '新宿' },
            { id: 'shibuya', name: '渋谷・原宿' },
            { id: 'ginza', name: '銀座' },
            { id: 'odaiba', name: 'お台場' },
            { id: 'tokyo-sta', name: '丸の内・東京駅' },
            { id: 'ueno', name: '上野' },
            { id: 'roppongi', name: '六本木' },
        ],
        spots: [
            { n: '浅草寺・雷門', d: '東京最古の寺院と仲見世通り', t: '観光', dur: 90, addr: '台東区浅草', area: 'asakusa', th: ['sg', 'hs'], pop: 5 },
            { n: '東京スカイツリー', d: '634mの世界一の電波塔', t: '観光', dur: 120, addr: '墨田区押上', area: 'asakusa', th: ['sg', 'np', 'cp', 'ng'], pop: 5 },
            { n: '渋谷スクランブル交差点', d: '世界一有名な交差点', t: '観光', dur: 30, addr: '渋谷区道玄坂', area: 'shibuya', th: ['sg'], pop: 5 },
            { n: 'SHIBUYA SKY', d: '渋谷の絶景展望台。屋上テラスが圧巻', t: '観光', dur: 90, addr: '渋谷区渋谷', area: 'shibuya', th: ['np', 'cp', 'ng'], pop: 5, bk: true },
            { n: '明治神宮', d: '都心の鎮守の杜。原宿のすぐ近く', t: '観光', dur: 75, addr: '渋谷区代々木神園町', area: 'shibuya', th: ['sg', 'hs'], pop: 4 },
            { n: '原宿・竹下通り', d: 'カワイイ文化の発信地', t: '観光', dur: 60, addr: '渋谷区神宮前', area: 'shibuya', th: ['sg', 'sp'], pop: 4 },
            { n: '銀座中央通り', d: '高級ブランドと老舗が並ぶ目抜き通り', t: '観光', dur: 75, addr: '中央区銀座', area: 'ginza', th: ['sg', 'sp'], pop: 4 },
            { n: '皇居外苑・二重橋', d: '皇居前広場の絶景', t: '観光', dur: 60, addr: '千代田区皇居外苑', area: 'tokyo-sta', th: ['sg', 'hs'], pop: 3 },
            { n: '東京駅丸の内駅舎', d: '赤レンガの歴史的駅舎', t: '観光', dur: 30, addr: '千代田区丸の内', area: 'tokyo-sta', th: ['sg', 'hs'], pop: 4 },
            { n: '丸の内仲通り', d: 'おしゃれカフェと並木道', t: '観光', dur: 60, addr: '千代田区丸の内', area: 'tokyo-sta', th: ['sg', 'cp', 'sp'], pop: 3 },
            { n: '東京タワー', d: '昭和のシンボルタワー', t: '観光', dur: 90, addr: '港区芝公園', area: 'roppongi', th: ['sg', 'np', 'ng', 'cp'], pop: 4 },
            { n: '六本木ヒルズ展望台 東京シティビュー', d: '六本木の絶景パノラマ', t: '観光', dur: 90, addr: '港区六本木', area: 'roppongi', th: ['np', 'ng', 'cp'], pop: 4 },
            { n: 'お台場海浜公園', d: 'レインボーブリッジを望むビーチ', t: '観光', dur: 60, addr: '港区台場', area: 'odaiba', th: ['sg', 'cp', 'fm'], pop: 4 },
            { n: 'チームラボボーダレス お台場', d: 'デジタルアートの没入空間', t: '観光', dur: 180, addr: '港区台場', area: 'odaiba', th: ['ar', 'cp', 'fm'], pop: 5, bk: true },
            { n: 'チームラボプラネッツTOKYO 豊洲', d: '水に入る体感型アート', t: '観光', dur: 120, addr: '江東区豊洲', area: 'odaiba', th: ['ar', 'cp'], pop: 5, bk: true },
            { n: '上野恩賜公園・上野動物園', d: '桜の名所と歴史ある動物園', t: '観光', dur: 150, addr: '台東区上野公園', area: 'ueno', th: ['sg', 'fm', 'np'], pop: 4 },
            { n: '東京国立博物館', d: '日本最大の博物館。国宝多数', t: '観光', dur: 120, addr: '台東区上野公園', area: 'ueno', th: ['sg', 'hs', 'ar'], pop: 4 },
            { n: '新宿御苑', d: '都心のオアシス。桜の名所', t: '観光', dur: 90, addr: '新宿区内藤町', area: 'shinjuku', th: ['sg', 'np', 'cp'], pop: 3 },
            { n: '東京都庁 北展望室', d: '無料で楽しめる新宿の絶景', t: '観光', dur: 60, addr: '新宿区西新宿', area: 'shinjuku', th: ['sg', 'np'], pop: 4 },
            { n: '思い出横丁', d: '新宿西口の昭和レトロ横丁', t: 'グルメ', dur: 75, addr: '新宿区西新宿', area: 'shinjuku', th: ['gm', 'ng'], pop: 4, eveningOk: true },
            { n: '築地場外市場', d: '海鮮丼と寿司の聖地', t: 'グルメ', dur: 90, addr: '中央区築地', area: 'tokyo-sta', th: ['gm', 'sg'], pop: 5, morningOk: true },
            { n: '豊洲市場', d: '魚河岸の最新拠点', t: 'グルメ', dur: 90, addr: '江東区豊洲', area: 'odaiba', th: ['gm', 'sg'], pop: 4, morningOk: true },
            { n: 'もんじゃストリート 月島', d: '本場のもんじゃ焼き発祥地', t: 'グルメ', dur: 90, addr: '中央区月島', area: 'tokyo-sta', th: ['gm', 'fm'], pop: 4 },
            { n: '一蘭 渋谷店', d: '個室で味わう本格とんこつラーメン', t: 'グルメ', dur: 45, addr: '渋谷区宇田川町', area: 'shibuya', th: ['gm'], pop: 3 },
            { n: '梅丘寿司の美登利 総本店', d: '行列の絶えない人気寿司店', t: 'グルメ', dur: 90, addr: '世田谷区梅丘', area: 'shibuya', th: ['gm'], pop: 4 },
            { n: 'ginza KYUBEY', d: '銀座の名店、職人技の江戸前寿司', t: 'グルメ', dur: 120, addr: '中央区銀座', area: 'ginza', th: ['gm', 'cp'], pop: 5, bk: true },
            { n: '東京ディズニーシー', d: '世界唯一の海をテーマにしたディズニー', t: '観光', dur: 600, addr: '浦安市舞浜', area: 'odaiba', th: ['fm', 'cp', 'ex'], pop: 5, bk: true },
            { n: '東京ディズニーランド', d: '世界中で愛される夢の王国', t: '観光', dur: 600, addr: '浦安市舞浜', area: 'odaiba', th: ['fm', 'cp', 'ex'], pop: 5, bk: true },
        ],
        hotels: [
            { n: 'ザ・リッツ・カールトン東京', addr: '港区赤坂', area: 'roppongi', price: 95000 },
            { n: 'パークハイアット東京', addr: '新宿区西新宿', area: 'shinjuku', price: 78000 },
            { n: 'ホテルメトロポリタン 丸の内', addr: '千代田区丸の内', area: 'tokyo-sta', price: 32000 },
            { n: '東急ステイ銀座', addr: '中央区銀座', area: 'ginza', price: 22000 },
            { n: '浅草ビューホテル', addr: '台東区西浅草', area: 'asakusa', price: 19000 },
            { n: 'シェラトン・グランデ・トーキョーベイ・ホテル', addr: '浦安市舞浜', area: 'odaiba', price: 35000 },
        ],
        titleHints: {
            sg: ['東京定番観光', '王道スポット'],
            gm: ['東京グルメ', '名店巡り'],
            sp: ['ショッピング', '原宿・銀座'],
            ar: ['ミュージアム巡り', 'アート体験'],
            ng: ['東京夜景', 'スカイツリーと夜景'],
            fm: ['ディズニーと家族旅'],
        },
    },

    // ========================================
    // 5. 大阪・USJ
    // ========================================
    {
        id: 'osaka', name: '大阪', country: '日本', region: 'kansai',
        trip_style: 'public_transit', intra_mode: '電車', intra_gap_min: 25,
        themes: ['sg', 'gm', 'fm', 'cp', 'sp', 'ng'],
        areas: [
            { id: 'umeda', name: '梅田' },
            { id: 'namba', name: 'なんば・心斎橋' },
            { id: 'osaka-castle', name: '大阪城' },
            { id: 'usj', name: 'USJ周辺' },
            { id: 'tsutenkaku', name: '通天閣・新世界' },
        ],
        spots: [
            { n: 'ユニバーサル・スタジオ・ジャパン', d: '関西最大のテーマパーク', t: '観光', dur: 600, addr: '此花区桜島', area: 'usj', th: ['fm', 'cp', 'ex'], pop: 5, bk: true },
            { n: '大阪城天守閣', d: '豊臣秀吉が築いた天下の名城', t: '観光', dur: 90, addr: '中央区大阪城', area: 'osaka-castle', th: ['sg', 'hs'], pop: 5 },
            { n: '道頓堀', d: 'グリコ看板と食い倒れの街', t: '観光', dur: 90, addr: '中央区道頓堀', area: 'namba', th: ['sg', 'gm', 'ng'], pop: 5 },
            { n: '心斎橋筋商店街', d: '関西最大級のショッピングストリート', t: '観光', dur: 90, addr: '中央区心斎橋', area: 'namba', th: ['sp', 'sg'], pop: 4 },
            { n: '梅田スカイビル空中庭園', d: '梅田の絶景展望スポット', t: '観光', dur: 75, addr: '北区大淀中', area: 'umeda', th: ['np', 'cp', 'ng'], pop: 4 },
            { n: 'HEP FIVE観覧車', d: '梅田の赤い観覧車', t: '観光', dur: 45, addr: '北区角田町', area: 'umeda', th: ['sg', 'cp'], pop: 3 },
            { n: '通天閣', d: '新世界のシンボルタワー', t: '観光', dur: 60, addr: '浪速区恵美須東', area: 'tsutenkaku', th: ['sg', 'np'], pop: 4 },
            { n: '新世界', d: '串カツの発祥地と昭和レトロ', t: '観光', dur: 75, addr: '浪速区恵美須東', area: 'tsutenkaku', th: ['sg', 'gm'], pop: 4 },
            { n: 'あべのハルカス展望台', d: '日本一の高さ300m', t: '観光', dur: 90, addr: '阿倍野区阿倍野筋', area: 'tsutenkaku', th: ['np', 'cp', 'ng'], pop: 4 },
            { n: '海遊館', d: '世界最大級の水族館', t: '観光', dur: 180, addr: '港区海岸通', area: 'usj', th: ['fm', 'sg'], pop: 4 },
            { n: '天保山大観覧車', d: '海遊館隣の大観覧車', t: '観光', dur: 45, addr: '港区海岸通', area: 'usj', th: ['cp', 'fm', 'np'], pop: 3 },
            { n: '中之島 バラ園', d: '都心のバラ園と図書館建築', t: '観光', dur: 60, addr: '北区中之島', area: 'umeda', th: ['sg', 'np', 'cp'], pop: 3 },
            { n: '黒門市場', d: '大阪の台所と呼ばれる活気ある市場', t: 'グルメ', dur: 75, addr: '中央区日本橋', area: 'namba', th: ['gm', 'sg'], pop: 4 },
            { n: 'はり重 グリル', d: '道頓堀の老舗ステーキ', t: 'グルメ', dur: 90, addr: '中央区道頓堀', area: 'namba', th: ['gm', 'hs'], pop: 4 },
            { n: 'たこ家道頓堀くくる', d: '本場のたこ焼きを食べ歩き', t: 'グルメ', dur: 30, addr: '中央区道頓堀', area: 'namba', th: ['gm', 'sg'], pop: 5 },
            { n: '会津屋 梅田店', d: 'たこ焼き発祥の老舗', t: 'グルメ', dur: 45, addr: '北区芝田', area: 'umeda', th: ['gm', 'hs'], pop: 3 },
            { n: 'お好み焼 きじ 本店', d: '梅田スカイビル地下の名店', t: 'グルメ', dur: 60, addr: '北区大淀中', area: 'umeda', th: ['gm'], pop: 5 },
            { n: '北極星 心斎橋本店', d: 'オムライス発祥の老舗洋食', t: 'グルメ', dur: 60, addr: '中央区西心斎橋', area: 'namba', th: ['gm', 'hs'], pop: 4 },
            { n: '551蓬莱 本店', d: '関西人のソウルフード豚まん', t: 'グルメ', dur: 30, addr: '中央区難波', area: 'namba', th: ['gm'], pop: 4 },
            { n: '万博記念公園 太陽の塔', d: '岡本太郎の傑作と万博公園', t: '観光', dur: 120, addr: '吹田市千里万博公園', area: 'umeda', th: ['sg', 'ar', 'fm'], pop: 4 },
        ],
        hotels: [
            { n: 'コンラッド大阪', addr: '北区中之島', area: 'umeda', price: 58000 },
            { n: 'ホテルユニバーサルポート', addr: '此花区桜島', area: 'usj', price: 24000 },
            { n: 'ホテル日航大阪', addr: '中央区西心斎橋', area: 'namba', price: 28000 },
            { n: '大阪マリオット都ホテル', addr: '阿倍野区阿倍野筋', area: 'tsutenkaku', price: 35000 },
            { n: 'ザ・パークフロントホテル アット ユニバーサル・スタジオ・ジャパン', addr: '此花区島屋', area: 'usj', price: 30000 },
        ],
        titleHints: {
            sg: ['大阪定番', 'ミナミとキタ'],
            gm: ['粉モンとグルメ', 'たこ焼き・お好み焼き'],
            fm: ['USJと家族旅'],
            cp: ['夜の道頓堀', 'デート定番'],
        },
    },
]

// このファイルは京都・沖縄本島・札幌小樽・東京・大阪を含む
