import type { Route } from '../types'

// 追加ルート 第3弾
// 国内ニッチ3＋海外（インド・スリランカ・ネパール・ブータン・中国深部・
// ヨルダン・南アフリカ・ナミビア・NZ・ケアンズ・シカゴ・アラスカ・
// ガラパゴス・ハバナ）

export const ROUTES_EXTRA_2: Route[] = [
    // ──────────── 国内ニッチ 3 ────────────
    {
        id: 'r-nasu-kinugawa',
        name: '那須・鬼怒川',
        legs: [{ destinationId: 'nasu-kinugawa', days: 2 }],
        suitableThemes: ['on', 'fm', 'cp', 'np'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [2, 3],
        popularity: 4,
        titleSuffixes: ['那須高原と鬼怒川', '動物王国と温泉', '家族で楽しむ高原リゾート', '東武ワールドスクウェアも'],
    },
    {
        id: 'r-aizu',
        name: '会津・大内宿',
        legs: [{ destinationId: 'aizu', days: 2 }],
        suitableThemes: ['sg', 'hs', 'on'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['鶴ヶ城と白虎隊', '大内宿の茅葺き集落', '五色沼と裏磐梯'],
    },
    {
        id: 'r-chichibu-kawagoe',
        name: '秩父・川越・長瀞',
        legs: [{ destinationId: 'chichibu-kawagoe', days: 2 }],
        suitableThemes: ['sg', 'hs', 'np', 'cp'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [2, 3],
        popularity: 4,
        titleSuffixes: ['小江戸川越と秩父', '川越散策と長瀞ライン下り', '三峯神社と芝桜の丘', '埼玉ノスタルジー旅'],
    },
    {
        id: 'r-shiga',
        name: '滋賀（彦根・近江八幡）',
        legs: [{ destinationId: 'shiga', days: 2 }],
        suitableThemes: ['sg', 'hs', 'gm', 'np'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['彦根城と近江八幡', '琵琶湖とラコリーナ', '比叡山延暦寺'],
    },
    {
        id: 'r-himeji',
        name: '姫路',
        legs: [{ destinationId: 'himeji', days: 1 }],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [1, 2],
        popularity: 3,
        titleSuffixes: ['白鷺城世界遺産', '姫路城と好古園'],
    },
    {
        id: 'r-takamatsu',
        name: '高松・琴平',
        legs: [{ destinationId: 'takamatsu', days: 2 }],
        suitableThemes: ['sg', 'gm', 'hs', 'np'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [2, 3],
        popularity: 4,
        titleSuffixes: ['栗林公園と讃岐うどん', '金刀比羅宮と高松城', '父母ヶ浜とうどん巡礼', '小豆島フェリー'],
    },
    {
        id: 'r-iya',
        name: '徳島・祖谷渓',
        legs: [{ destinationId: 'iya', days: 2 }],
        suitableThemes: ['np', 'on', 'nt', 'ex'],
        suitableOrigins: ['東京', '大阪', '福岡'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['鳴門の渦潮と祖谷渓', 'かずら橋と大塚国際美術館', '秘境祖谷温泉'],
    },
    {
        id: 'r-shimonoseki',
        name: '下関・関門',
        legs: [{ destinationId: 'shimonoseki', days: 2 }],
        suitableThemes: ['gm', 'sg', 'hs', 'np'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [2, 3],
        popularity: 4,
        titleSuffixes: ['ふぐと関門海峡', '門司港レトロと角島大橋', '元乃隅神社と巌流島', '海峡を渡る旅'],
    },
    {
        id: 'r-saga-ureshino',
        name: '嬉野・唐津',
        legs: [{ destinationId: 'saga-ureshino', days: 2 }],
        suitableThemes: ['on', 'hs', 'sg', 'gm'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['美肌の湯と唐津城', '武雄温泉と御船山楽園', '佐賀の世界遺産と温泉'],
    },
    {
        id: 'r-miyazaki',
        name: '宮崎・日南',
        legs: [{ destinationId: 'miyazaki', days: 2 }],
        suitableThemes: ['np', 'sg', 'hs', 'gm'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['青島神社とサンメッセ日南', '飫肥城下町とチキン南蛮', '日南海岸絶景ドライブ'],
    },
    {
        id: 'r-amami',
        name: '奄美大島',
        legs: [{ destinationId: 'amami', days: 3 }],
        suitableThemes: ['np', 'nt', 'wh', 'bc'],
        suitableOrigins: ['東京', '大阪', '福岡'],
        durations: [3, 4],
        popularity: 3,
        titleSuffixes: ['世界遺産の亜熱帯原生林', 'マングローブとハートロック', '奄美ブルーと黒糖焼酎'],
    },
    {
        id: 'r-akita-oga',
        name: '秋田・男鹿',
        legs: [{ destinationId: 'akita-oga', days: 2 }],
        suitableThemes: ['sg', 'hs', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [2, 3],
        popularity: 2,
        titleSuffixes: ['なまはげと男鹿半島', '秋田犬とゴジラ岩'],
    },
    {
        id: 'r-echigo-yuzawa',
        name: '越後湯沢・苗場',
        legs: [{ destinationId: 'echigo-yuzawa', days: 2 }],
        suitableThemes: ['on', 'ex', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [2, 3],
        seasonal: 'winter',
        titlePrefix: '冬の',
        popularity: 3,
        titleSuffixes: ['苗場スキー＆温泉', '雪国の湯と地酒', 'ドラゴンドラと粉雪'],
    },
    {
        id: 'r-kerama',
        name: '慶良間諸島',
        legs: [{ destinationId: 'kerama', days: 3 }],
        suitableThemes: ['bc', 'np', 'ex', 'cp'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [3, 4],
        popularity: 4,
        titleSuffixes: ['ケラマブルー満喫', '渡嘉敷と座間味のビーチ', 'ザトウクジラとシュノーケル', 'ハネムーン慶良間'],
    },

    // ──────────── 国内コンビ追加（既存+ニッチ） ────────────
    {
        id: 'r-kansai-shiga',
        name: '京都・滋賀',
        legs: [
            { destinationId: 'kyoto', days: 2 },
            { destinationId: 'shiga', days: 1 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '名古屋', '福岡'],
        durations: [3, 4],
        popularity: 3,
        titleSuffixes: ['古都と琵琶湖', '京都と彦根城', '世界遺産巡り'],
    },
    {
        id: 'r-hiroshima-shimonoseki',
        name: '広島・下関',
        legs: [
            { destinationId: 'hiroshima-miyajima', days: 2 },
            { destinationId: 'shimonoseki', days: 1 },
        ],
        suitableThemes: ['sg', 'wh', 'gm'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [3, 4],
        popularity: 3,
        titleSuffixes: ['広島＋下関ふぐ', '宮島とふぐ料理', '山陽グルメ周遊'],
    },

    // ──────────── インド ────────────
    {
        id: 'r-india-golden',
        name: 'インド・ゴールデントライアングル',
        legs: [{ destinationId: 'india-golden', days: 6 }],
        suitableThemes: ['sg', 'hs', 'wh', 'ar'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 4,
        titleSuffixes: ['タージマハルと宮殿巡り', 'デリー＋アグラ＋ジャイプール', 'ムガル帝国を辿る', 'インド3大都市世界遺産'],
    },

    // ──────────── スリランカ ────────────
    {
        id: 'r-srilanka',
        name: 'スリランカ',
        legs: [{ destinationId: 'srilanka', days: 6 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 4,
        titleSuffixes: ['シーギリヤとキャンディ', '8つの世界遺産巡り', '紅茶畑と山岳列車', 'インド洋の真珠'],
    },

    // ──────────── ネパール ────────────
    {
        id: 'r-nepal',
        name: 'ネパール',
        legs: [{ destinationId: 'nepal', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['カトマンズと世界遺産', 'ヒマラヤ展望飛行', 'ポカラとフェワ湖'],
    },

    // ──────────── ブータン ────────────
    {
        id: 'r-bhutan',
        name: 'ブータン',
        legs: [{ destinationId: 'bhutan', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['タクツァン僧院と幸せの国', 'パロ・ティンプー・プナカ', 'GNHを体験する旅'],
    },
    {
        id: 'r-nepal-bhutan',
        name: 'ネパール・ブータン',
        legs: [
            { destinationId: 'nepal', days: 4 },
            { destinationId: 'bhutan', days: 4 },
        ],
        suitableThemes: ['sg', 'hs', 'wh', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [9, 10, 11],
        popularity: 2,
        titleSuffixes: ['ヒマラヤ2か国', 'ネパール＋ブータン'],
    },

    // ──────────── 中国深部 ────────────
    {
        id: 'r-guilin',
        name: '桂林・陽朔',
        legs: [{ destinationId: 'guilin', days: 4 }],
        suitableThemes: ['np', 'sg', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6],
        popularity: 3,
        titleSuffixes: ['漓江下りと象鼻山', 'カルスト地形絶景', '龍脊棚田の絶景'],
    },
    {
        id: 'r-chengdu-jiuzhaigou',
        name: '成都・九寨溝',
        legs: [{ destinationId: 'chengdu-jiuzhaigou', days: 5 }],
        suitableThemes: ['np', 'nt', 'wh', 'sg', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7],
        popularity: 3,
        titleSuffixes: ['パンダと九寨溝', '世界遺産湖群と四川料理', '成都と楽山大仏'],
    },

    // ──────────── ヨルダン ────────────
    {
        id: 'r-jordan',
        name: 'ヨルダン（ペトラ）',
        legs: [{ destinationId: 'jordan', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 4,
        titleSuffixes: ['ペトラ遺跡と死海', '岩窟都市とワディラム', '新世界七不思議', '中東古代世界遺産'],
    },
    {
        id: 'r-jordan-egypt',
        name: 'ヨルダン＋エジプト',
        legs: [
            { destinationId: 'jordan', days: 3 },
            { destinationId: 'egypt', days: 4 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10],
        popularity: 2,
        titleSuffixes: ['中東2大遺跡', 'ペトラ＋ピラミッド'],
    },

    // ──────────── 南アフリカ ────────────
    {
        id: 'r-south-africa',
        name: '南アフリカ',
        legs: [{ destinationId: 'cape-town', days: 6 }],
        suitableThemes: ['np', 'nt', 'sg', 'gm', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9, 10],
        popularity: 3,
        titleSuffixes: ['ケープタウンとサファリ', '喜望峰とテーブルマウンテン', 'ワインランドとクルーガー', '南アフリカ大周遊'],
    },

    // ──────────── ナミビア ────────────
    {
        id: 'r-namibia',
        name: 'ナミビア',
        legs: [{ destinationId: 'namibia', days: 5 }],
        suitableThemes: ['np', 'nt', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 2,
        titleSuffixes: ['ナミブ砂漠とデッドフレイ', 'エトーシャサファリ', 'アフリカ秘境絶景'],
    },

    // ──────────── ニュージーランド ────────────
    {
        id: 'r-nz',
        name: 'ニュージーランド南北',
        legs: [{ destinationId: 'newzealand', days: 7 }],
        suitableThemes: ['np', 'nt', 'ex', 'cp', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10],
        popularity: 5,
        titleSuffixes: ['南北周遊', 'ミルフォードサウンドとロトルア', 'ロードオブザリングの世界', 'マウントクックとテカポ', 'NZ大絶景縦断'],
    },
    {
        id: 'r-nz-south',
        name: 'NZ南島（クイーンズタウン・マウントクック）',
        legs: [{ destinationId: 'newzealand', days: 6 }],
        suitableThemes: ['np', 'nt', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7],
        popularity: 3,
        titleSuffixes: ['南島絶景ハイライト', 'クイーンズタウン＋マウントクック', 'テカポ星空'],
    },

    // ──────────── ケアンズ ────────────
    {
        id: 'r-cairns',
        name: 'ケアンズ・GBR',
        legs: [{ destinationId: 'cairns', days: 4 }],
        suitableThemes: ['np', 'nt', 'bc', 'fm', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [4, 5, 6],
        popularity: 5,
        titleSuffixes: ['世界遺産2つ・GBRと熱帯雨林', 'グリーン島シュノーケル', 'キュランダ高原列車', '家族で楽しむケアンズ', 'ハミルトン島リゾート'],
    },
    {
        id: 'r-sydney-cairns',
        name: 'シドニー・ケアンズ',
        legs: [
            { destinationId: 'sydney', days: 3 },
            { destinationId: 'cairns', days: 3 },
        ],
        suitableThemes: ['sg', 'np', 'bc'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 4,
        titleSuffixes: ['豪州東部周遊', 'シドニー＋GBR', 'オペラハウスと珊瑚礁'],
    },

    // ──────────── 北米詳細 ────────────
    {
        id: 'r-chicago',
        name: 'シカゴ',
        legs: [{ destinationId: 'chicago', days: 3 }],
        suitableThemes: ['sg', 'ar', 'gm', 'sp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [4, 5],
        popularity: 2,
        titleSuffixes: ['ザ・ビーンと建築美', 'シカゴ美術館とピザ'],
    },
    {
        id: 'r-alaska',
        name: 'アラスカ',
        legs: [{ destinationId: 'alaska', days: 5 }],
        suitableThemes: ['np', 'nt', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        seasonal: 'winter',
        titlePrefix: '冬の',
        popularity: 3,
        titleSuffixes: ['オーロラとデナリ', 'チェナ温泉と犬ぞり', '氷河と原生林'],
    },

    // ──────────── 中南米 ────────────
    {
        id: 'r-galapagos',
        name: 'ガラパゴス諸島',
        legs: [{ destinationId: 'galapagos', days: 6 }],
        suitableThemes: ['nt', 'np', 'wh', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9, 10],
        popularity: 3,
        titleSuffixes: ['進化論の島と固有種', 'ゾウガメとアシカ', 'ガラパゴスクルーズ'],
    },
    {
        id: 'r-havana',
        name: 'ハバナ（キューバ）',
        legs: [{ destinationId: 'havana', days: 4 }],
        suitableThemes: ['sg', 'hs', 'wh', 'cp', 'gm', 'ng'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 3,
        titleSuffixes: ['オールド・ハバナとサルサ', 'クラシックカーとモヒート', 'カリブのレトロ社会主義'],
    },
    {
        id: 'r-cuba-cancun',
        name: 'キューバ＋カンクン',
        legs: [
            { destinationId: 'havana', days: 3 },
            { destinationId: 'cancun', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'bc'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8],
        popularity: 2,
        titleSuffixes: ['カリブ海2か国', 'ハバナ＋カンクン'],
    },

    // ──────────── アジア追加コンビ ────────────
    {
        id: 'r-india-srilanka',
        name: 'インド・スリランカ',
        legs: [
            { destinationId: 'india-golden', days: 4 },
            { destinationId: 'srilanka', days: 4 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [9, 10, 11],
        popularity: 2,
        titleSuffixes: ['南アジア2か国', 'タージマハル＋シーギリヤ'],
    },
    {
        id: 'r-thailand-cambodia',
        name: 'タイ＋カンボジア＋ベトナム',
        legs: [
            { destinationId: 'bangkok', days: 3 },
            { destinationId: 'angkor', days: 2 },
            { destinationId: 'hochiminh', days: 2 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 2,
        titleSuffixes: ['東南アジア3か国', 'バンコク＋アンコール＋ホーチミン'],
    },
]
