import type { Route } from '../types'

// 東京発の1泊2日プラン専用ルート。
// 既存 route との重複を避けるため、1泊2日固定の variant を多めに展開する。

export const ROUTES_1N2: Route[] = [
    // ──────────── 海・温泉系 ────────────
    {
        id: 'r-atami-1n2',
        name: '熱海',
        legs: [{ destinationId: 'atami', days: 2 }],
        suitableThemes: ['on', 'np', 'cp', 'gm', 'sg'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 6,
        titleSuffixes: ['東京から1時間の温泉旅', '熱海温泉と海絶景', 'カップル王道1泊2日', '駅近で気軽に行ける海街', 'MOA美術館と來宮神社', '熱海銀座食べ歩き'],
    },
    {
        id: 'r-ito-shimoda-1n2',
        name: '伊東・下田（東伊豆〜南伊豆）',
        legs: [{ destinationId: 'ito-shimoda', days: 2 }],
        suitableThemes: ['on', 'np', 'bc', 'cp', 'hs'],
        suitableOrigins: ['東京'],
        durations: [2, 3],
        popularity: 5,
        titleSuffixes: ['城ヶ崎吊橋と大室山', '白浜と下田開国ロード', '東伊豆温泉ドライブ', '南伊豆ビーチと金目鯛'],
    },
    {
        id: 'r-shuzenji-1n2',
        name: '修善寺・伊豆長岡',
        legs: [{ destinationId: 'shuzenji', days: 2 }],
        suitableThemes: ['on', 'sg', 'hs', 'cp', 'np'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 5,
        titleSuffixes: ['竹林の小径と修禅寺', '修善寺温泉カップル旅', '韮山反射炉と伊豆長岡', 'わさびと富士山ビュー'],
    },
    {
        id: 'r-ikaho-1n2',
        name: '伊香保温泉',
        legs: [{ destinationId: 'ikaho', days: 2 }],
        suitableThemes: ['on', 'cp', 'np', 'hs', 'gm'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 5,
        titleSuffixes: ['365段の石段街', '黄金の湯と榛名湖', '伊香保で水沢うどん', '東京から2時間半の温泉郷'],
    },
    {
        id: 'r-minakami-1n2',
        name: '水上温泉・谷川岳',
        legs: [{ destinationId: 'minakami', days: 2 }],
        suitableThemes: ['on', 'nt', 'np', 'ex', 'cp'],
        suitableOrigins: ['東京'],
        durations: [2, 3],
        popularity: 4,
        titleSuffixes: ['谷川岳ロープウェーと一ノ倉沢', '水上ラフティング体験', '宝川の超巨大露天風呂', 'もぐら駅と渓谷'],
    },
    {
        id: 'r-kawaji-1n2',
        name: '川治温泉・湯西川',
        legs: [{ destinationId: 'kawaji', days: 2 }],
        suitableThemes: ['on', 'hs', 'np', 'cp', 'nt'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 4,
        titleSuffixes: ['龍王峡ハイクと川治', '平家集落・湯西川の隠れ里', '冬のかまくら祭り', '鬼怒川上流の秘湯'],
    },
    {
        id: 'r-shibu-1n2',
        name: '渋温泉・地獄谷野猿',
        legs: [{ destinationId: 'shibu-yamanouchi', days: 2 }],
        suitableThemes: ['on', 'sg', 'hs', 'np', 'cp', 'ex'],
        suitableOrigins: ['東京'],
        durations: [2, 3],
        popularity: 5,
        titleSuffixes: ['九湯めぐりとスノーモンキー', '渋温泉の木造旅館', '温泉に入る猿と石畳', '志賀高原の麓へ'],
    },
    {
        id: 'r-ueda-bessho-1n2',
        name: '上田・別所温泉',
        legs: [{ destinationId: 'ueda-bessho', days: 2 }],
        suitableThemes: ['sg', 'hs', 'on', 'cp'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 4,
        titleSuffixes: ['真田の城下町と外湯巡り', '国宝八角三重塔', '上田電鉄で温泉郷へ', '北向観音と別所'],
    },
    {
        id: 'r-okunikko-1n2',
        name: '奥日光・中禅寺湖',
        legs: [{ destinationId: 'okunikko', days: 2 }],
        suitableThemes: ['nt', 'np', 'on', 'cp', 'wh'],
        suitableOrigins: ['東京'],
        durations: [2, 3],
        popularity: 5,
        titleSuffixes: ['華厳の滝と中禅寺湖', '戦場ヶ原ハイク', '湯元温泉の硫黄泉', '紅葉のいろは坂'],
    },

    // ──────────── 街・グルメ系 ────────────
    {
        id: 'r-minatomirai-1n2',
        name: '横浜・みなとみらい',
        legs: [{ destinationId: 'minatomirai', days: 2 }],
        suitableThemes: ['sg', 'ng', 'cp', 'gm', 'sp', 'fm', 'ar'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 6,
        titleSuffixes: ['みなとみらいと中華街', '横浜夜景と赤レンガ', 'カップル王道1泊2日', '元町ショッピングと中華街グルメ', '気軽に行ける港町', 'コスモワールド観覧車の夜'],
    },
    {
        id: 'r-kawagoe-1n2',
        name: '川越（小江戸）',
        legs: [{ destinationId: 'kawagoe-koedo', days: 2 }],
        suitableThemes: ['sg', 'hs', 'gm', 'cp', 'sp'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 5,
        titleSuffixes: ['蔵の街・小江戸散策', '時の鐘と菓子屋横丁', '川越氷川神社・縁結び', 'うなぎとCOEDOビール'],
    },
    {
        id: 'r-enoshima-shonan-1n2',
        name: '江ノ島・湘南',
        legs: [{ destinationId: 'enoshima-shonan', days: 2 }],
        suitableThemes: ['sg', 'np', 'cp', 'bc', 'gm'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 5,
        titleSuffixes: ['江島神社と稲村ヶ崎の夕日', 'しらす丼と岩屋洞窟', '湘南ドライブと葉山', 'カップル王道日帰り×温泉'],
    },

    // ──────────── 自然・絶景系 ────────────
    {
        id: 'r-boso-uchibo-1n2',
        name: '房総内房（館山・鋸山）',
        legs: [{ destinationId: 'boso-uchibo', days: 2 }],
        suitableThemes: ['np', 'bc', 'cp', 'fm', 'gm'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 4,
        titleSuffixes: ['鋸山の地獄のぞき', '館山夕日桟橋', '東京湾アクアラインで内房へ', '沖ノ島シュノーケリング'],
    },
    {
        id: 'r-boso-sotobo-1n2',
        name: '房総外房（鴨川・勝浦）',
        legs: [{ destinationId: 'boso-sotobo', days: 2 }],
        suitableThemes: ['fm', 'np', 'bc', 'on', 'gm'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 5,
        titleSuffixes: ['鴨川シーワールドと家族旅', '養老渓谷の自然', '勝浦タンタンメンと朝市', '外房の海カフェ'],
    },
    {
        id: 'r-mito-oarai-1n2',
        name: '水戸・大洗',
        legs: [{ destinationId: 'mito-oarai', days: 2 }],
        suitableThemes: ['sg', 'np', 'hs', 'fm', 'gm'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 4,
        titleSuffixes: ['偕楽園と神磯の鳥居', 'アクアワールドと家族旅', 'ひたち海浜公園のネモフィラ', '袋田の滝と水戸'],
    },
    {
        id: 'r-choshi-1n2',
        name: '銚子・犬吠埼',
        legs: [{ destinationId: 'choshi', days: 2 }],
        suitableThemes: ['np', 'gm', 'cp', 'sg', 'fm'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 4,
        titleSuffixes: ['犬吠埼の朝日と灯台', '銚子電鉄とぬれ煎餅', '屛風ヶ浦・東洋のドーバー', '港町の海鮮丼'],
    },
    {
        id: 'r-okutama-mitake-1n2',
        name: '奥多摩・御岳',
        legs: [{ destinationId: 'okutama-mitake', days: 2 }],
        suitableThemes: ['nt', 'np', 'ex', 'on', 'cp'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 4,
        titleSuffixes: ['御岳山と武蔵御嶽神社', '日原鍾乳洞と渓谷', '奥多摩湖ハイク', 'もえぎの湯と山ごはん'],
    },
    {
        id: 'r-izu-oshima-1n2',
        name: '伊豆大島',
        legs: [{ destinationId: 'izu-oshima', days: 2 }],
        suitableThemes: ['np', 'nt', 'ex', 'bc'],
        suitableOrigins: ['東京'],
        durations: [2, 3],
        popularity: 4,
        titleSuffixes: ['三原山と裏砂漠', '波浮港と地層大切断面', '高速ジェット船で離島へ', '島の温泉と椿園'],
    },
    {
        id: 'r-yatsugatake-1n2',
        name: '八ヶ岳・清里',
        legs: [{ destinationId: 'yatsugatake-kiyosato', days: 2 }],
        suitableThemes: ['np', 'nt', 'cp', 'fm', 'gm'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 5,
        titleSuffixes: ['清泉寮ソフトクリーム', '八ヶ岳南麓ドライブ', '萌木の村と高原カフェ', 'リゾナーレ八ヶ岳ステイ'],
    },
    {
        id: 'r-yamanashi-wine-1n2',
        name: '山梨ワイナリー（甲府・勝沼）',
        legs: [{ destinationId: 'yamanashi-wine', days: 2 }],
        suitableThemes: ['gm', 'cp', 'sg', 'on', 'np'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 4,
        titleSuffixes: ['勝沼ワインカーヴ巡り', '昇仙峡の渓谷美', '甲府盆地で大人デート', 'ほうとうと石和温泉'],
    },

    // ──────────── 歴史・体験系 ────────────
    {
        id: 'r-takasaki-tomioka-1n2',
        name: '高崎・富岡',
        legs: [{ destinationId: 'takasaki-tomioka', days: 2 }],
        suitableThemes: ['sg', 'hs', 'wh', 'gm', 'fm'],
        suitableOrigins: ['東京'],
        durations: [2],
        popularity: 3,
        titleSuffixes: ['富岡製糸場と世界遺産', 'こんにゃくパークとガトーフェスタ', '高崎パスタとだるま寺', '妙義山と磯部温泉'],
    },
]
