import type { Route } from '../types'

// 海外追加 第5弾：抜けていた有名旅行先（バンクーバー・オーロラ・カッパドキア他）

export const ROUTES_EXTRA_5: Route[] = [
    // ──────────── カナダ追加 ────────────
    {
        id: 'r-vancouver',
        name: 'バンクーバー',
        legs: [{ destinationId: 'vancouver', days: 4 }],
        suitableThemes: ['sg', 'np', 'nt', 'gm', 'cp'],
        suitableOrigins: ['東京'],
        durations: [5, 6, 7],
        popularity: 4,
        titleSuffixes: ['スタンレーパークとガスタウン', 'バンクーバー王道', 'ビクトリア日帰り', '西カナダの玄関口'],
    },
    {
        id: 'r-yellowknife',
        name: 'イエローナイフ（オーロラ）',
        legs: [{ destinationId: 'yellowknife', days: 3 }],
        suitableThemes: ['np', 'nt', 'ex', 'cp'],
        suitableOrigins: ['東京'],
        durations: [4, 5, 6],
        popularity: 5,
        titleSuffixes: ['世界屈指のオーロラ', 'オーロラビレッジと犬ぞり', '極北の絶景旅', '冬のカナダ・オーロラ'],
    },
    {
        id: 'r-banff-jasper',
        name: 'バンフ・ジャスパー（カナディアンロッキー）',
        legs: [{ destinationId: 'banff-jasper', days: 6 }],
        suitableThemes: ['np', 'nt', 'wh', 'cp'],
        suitableOrigins: ['東京'],
        durations: [7, 8, 9],
        popularity: 5,
        titleSuffixes: ['モレーン湖とルイーズ湖', 'アイスフィールズパークウェイ', 'カナディアンロッキー大絶景', 'バンフ＋ジャスパー縦断'],
    },
    {
        id: 'r-vancouver-banff',
        name: 'バンクーバー＋バンフ',
        legs: [
            { destinationId: 'vancouver', days: 3 },
            { destinationId: 'banff-jasper', days: 4 },
        ],
        suitableThemes: ['np', 'nt', 'wh'],
        suitableOrigins: ['東京'],
        durations: [8, 9, 10],
        popularity: 5,
        titleSuffixes: ['西カナダ大周遊', 'バンクーバー＋カナディアンロッキー', 'カナダ西部ハイライト'],
    },

    // ──────────── トルコ拡充 ────────────
    {
        id: 'r-cappadocia',
        name: 'カッパドキア',
        legs: [{ destinationId: 'cappadocia', days: 4 }],
        suitableThemes: ['np', 'wh', 'ex', 'sg', 'cp'],
        suitableOrigins: ['東京'],
        durations: [5, 6, 7],
        popularity: 5,
        titleSuffixes: ['気球と奇岩の絶景', 'ギョレメと地下都市', '洞窟ホテル滞在', 'カッパドキア大満喫'],
    },
    {
        id: 'r-istanbul',
        name: 'イスタンブール',
        legs: [{ destinationId: 'istanbul', days: 4 }],
        suitableThemes: ['sg', 'hs', 'wh', 'gm', 'sp', 'ar'],
        suitableOrigins: ['東京'],
        durations: [5, 6, 7],
        popularity: 5,
        titleSuffixes: ['アヤソフィアとブルーモスク', 'ボスポラス海峡クルーズ', 'グランドバザールと旧市街', 'ヨーロッパとアジアの架け橋'],
    },
    {
        id: 'r-turkey-grand',
        name: 'トルコ大周遊（イスタンブール＋カッパドキア）',
        legs: [
            { destinationId: 'istanbul', days: 3 },
            { destinationId: 'cappadocia', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'wh', 'np'],
        suitableOrigins: ['東京'],
        durations: [7, 8, 9],
        popularity: 5,
        titleSuffixes: ['トルコ王道2都市', 'イスタンブール＋カッパドキア', 'オスマン帝国と気球'],
    },

    // ──────────── 中国追加 ────────────
    {
        id: 'r-xian',
        name: '西安・兵馬俑',
        legs: [{ destinationId: 'xian', days: 3 }],
        suitableThemes: ['sg', 'hs', 'wh', 'gm'],
        suitableOrigins: ['東京'],
        durations: [4, 5, 6],
        popularity: 4,
        titleSuffixes: ['兵馬俑と古都', '城壁と大雁塔', 'シルクロード起点', '回民街グルメ'],
    },
    {
        id: 'r-china-grand-xian',
        name: '中国三都＋西安',
        legs: [
            { destinationId: 'beijing', days: 3 },
            { destinationId: 'xian', days: 2 },
            { destinationId: 'shanghai', days: 2 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京'],
        durations: [8, 9, 10],
        popularity: 3,
        titleSuffixes: ['北京＋西安＋上海', '中国歴史大周遊'],
    },

    // ──────────── ヨーロッパ追加 ────────────
    {
        id: 'r-hallstatt',
        name: 'ハルシュタット',
        legs: [{ destinationId: 'hallstatt', days: 2 }],
        suitableThemes: ['sg', 'np', 'wh', 'cp'],
        suitableOrigins: ['東京'],
        durations: [3, 4, 5],
        popularity: 4,
        titleSuffixes: ['世界一美しい湖畔の村', '塩坑と湖クルーズ', 'ハルシュタット絶景'],
    },
    {
        id: 'r-vienna-hallstatt',
        name: 'ウィーン＋ハルシュタット',
        legs: [
            { destinationId: 'vienna', days: 3 },
            { destinationId: 'hallstatt', days: 2 },
        ],
        suitableThemes: ['sg', 'hs', 'np', 'cp'],
        suitableOrigins: ['東京'],
        durations: [6, 7, 8],
        popularity: 4,
        titleSuffixes: ['ウィーン＋ハルシュタット', 'オーストリア絶景巡り'],
    },
    {
        id: 'r-nice-monaco',
        name: '南仏（ニース・モナコ）',
        legs: [{ destinationId: 'nice-monaco', days: 5 }],
        suitableThemes: ['sg', 'np', 'cp', 'bc', 'gm', 'sp'],
        suitableOrigins: ['東京'],
        durations: [6, 7, 8],
        popularity: 4,
        titleSuffixes: ['コートダジュール絶景', 'ニース＋モナコ＋エズ', '地中海セレブ気分', 'モンテカルロとカンヌ'],
    },
    {
        id: 'r-paris-nice',
        name: 'パリ＋南仏',
        legs: [
            { destinationId: 'paris', days: 3 },
            { destinationId: 'nice-monaco', days: 3 },
        ],
        suitableThemes: ['sg', 'cp', 'gm'],
        suitableOrigins: ['東京'],
        durations: [7, 8, 9],
        popularity: 4,
        titleSuffixes: ['パリ＋コートダジュール', 'フランス王道'],
    },
    {
        id: 'r-cinque-terre',
        name: 'チンクエテッレ',
        legs: [{ destinationId: 'cinque-terre', days: 3 }],
        suitableThemes: ['np', 'wh', 'cp', 'bc', 'gm'],
        suitableOrigins: ['東京'],
        durations: [4, 5, 6],
        popularity: 4,
        titleSuffixes: ['5つの色彩あふれる村', 'リグーリア海岸', '愛の小径と村巡り'],
    },
    {
        id: 'r-italy-cinque',
        name: 'イタリア＋チンクエテッレ',
        legs: [
            { destinationId: 'florence', days: 2 },
            { destinationId: 'cinque-terre', days: 2 },
            { destinationId: 'milan', days: 2 },
        ],
        suitableThemes: ['sg', 'np', 'gm'],
        suitableOrigins: ['東京'],
        durations: [7, 8, 9],
        popularity: 4,
        titleSuffixes: ['フィレンツェ＋チンクエ＋ミラノ', '北イタリア大周遊'],
    },
    {
        id: 'r-tromso',
        name: 'トロムソ（北欧オーロラ）',
        legs: [{ destinationId: 'tromso', days: 4 }],
        suitableThemes: ['np', 'nt', 'ex', 'cp'],
        suitableOrigins: ['東京'],
        durations: [5, 6, 7],
        popularity: 4,
        titleSuffixes: ['北欧のオーロラ', 'トロムソ＋犬ぞり', 'ホエールウォッチング', 'サーミ族文化体験'],
    },
    {
        id: 'r-dolomites',
        name: 'ドロミテ',
        legs: [{ destinationId: 'dolomites', days: 4 }],
        suitableThemes: ['np', 'nt', 'wh', 'ex', 'cp'],
        suitableOrigins: ['東京'],
        durations: [5, 6, 7],
        popularity: 3,
        titleSuffixes: ['トレ・チーメと氷河湖', 'コルティナ・ダンペッツォ', 'ドロミテ絶景巡り'],
    },

    // ──────────── 中東・アフリカ追加 ────────────
    {
        id: 'r-marrakech',
        name: 'マラケシュ・サハラ',
        legs: [{ destinationId: 'marrakech', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'ex', 'sp'],
        suitableOrigins: ['東京'],
        durations: [5, 6, 7],
        popularity: 4,
        titleSuffixes: ['マラケシュとサハラ砂漠', 'ラクダ縦走と星空', 'ジャマ・エル・フナとスーク', 'マジョレル庭園とリヤド'],
    },
    {
        id: 'r-morocco-deep',
        name: 'モロッコ大周遊（マラケシュ＋シャウエン）',
        legs: [
            { destinationId: 'marrakech', days: 4 },
            { destinationId: 'morocco', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'ex'],
        suitableOrigins: ['東京'],
        durations: [8, 9, 10],
        popularity: 3,
        titleSuffixes: ['モロッコ全制覇', 'マラケシュ＋シャウエン＋サハラ'],
    },

    // ──────────── 東南アジア追加 ────────────
    {
        id: 'r-luang-prabang',
        name: 'ルアンパバーン',
        legs: [{ destinationId: 'luang-prabang', days: 3 }],
        suitableThemes: ['sg', 'hs', 'wh', 'cp', 'ex'],
        suitableOrigins: ['東京'],
        durations: [4, 5, 6],
        popularity: 3,
        titleSuffixes: ['托鉢の儀式と寺院', 'メコン川とクアンシーの滝', 'ラオス古都', 'プーシーの夕日'],
    },

    // ──────────── オセアニア追加 ────────────
    {
        id: 'r-fiji',
        name: 'フィジー',
        legs: [{ destinationId: 'fiji', days: 4 }],
        suitableThemes: ['bc', 'cp', 'np', 'ex', 'fm'],
        suitableOrigins: ['東京'],
        durations: [5, 6, 7],
        popularity: 4,
        titleSuffixes: ['マナ島とヤサワ諸島', 'シュノーケリング天国', 'フィジー伝統文化体験', 'ハネムーン王道'],
    },
    {
        id: 'r-palau',
        name: 'パラオ',
        legs: [{ destinationId: 'palau', days: 5 }],
        suitableThemes: ['bc', 'ex', 'np', 'nt'],
        suitableOrigins: ['東京'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['ジェリーフィッシュレイク', 'ロックアイランド', 'ダイビング天国'],
    },

    // ──────────── アメリカ国立公園 ────────────
    {
        id: 'r-yosemite',
        name: 'ヨセミテ国立公園',
        legs: [{ destinationId: 'yosemite', days: 4 }],
        suitableThemes: ['np', 'nt', 'wh', 'ex', 'fm'],
        suitableOrigins: ['東京'],
        durations: [5, 6, 7],
        popularity: 4,
        titleSuffixes: ['エル・キャピタンとハーフドーム', 'ヨセミテ滝と巨大セコイア', 'カリフォルニア絶景'],
    },
    {
        id: 'r-yellowstone',
        name: 'イエローストーン',
        legs: [{ destinationId: 'yellowstone', days: 5 }],
        suitableThemes: ['np', 'nt', 'wh', 'ex', 'fm'],
        suitableOrigins: ['東京'],
        durations: [6, 7, 8],
        popularity: 4,
        titleSuffixes: ['オールド・フェイスフルと間欠泉', 'グランド・プリズマティック温泉', '北米のセレンゲティ', 'グランドティトンも'],
    },
    {
        id: 'r-sf-yosemite',
        name: 'サンフランシスコ＋ヨセミテ',
        legs: [
            { destinationId: 'sf', days: 3 },
            { destinationId: 'yosemite', days: 3 },
        ],
        suitableThemes: ['sg', 'np', 'nt'],
        suitableOrigins: ['東京'],
        durations: [7, 8, 9],
        popularity: 4,
        titleSuffixes: ['SF＋ヨセミテ', '西海岸ハイライト'],
    },
]
