import type { Route } from '../types'

// 追加ルート（第2弾）
// 国内ニッチ + 南欧・中東欧 + 北米詳細 + ハネムーン専用

export const ROUTES_EXTRA: Route[] = [
    // ──────────── 国内ニッチ ────────────
    {
        id: 'r-ise-shima',
        name: '伊勢神宮・志摩',
        legs: [{ destinationId: 'ise-shima', days: 3 }],
        suitableThemes: ['sg', 'hs', 'gm', 'cp', 'fm'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [2, 3, 4],
        popularity: 5,
        titleSuffixes: ['お伊勢参りと志摩リゾート', '夫婦岩と海女体験', '伊勢神宮と鳥羽水族館', 'おかげ横丁と志摩'],
    },
    {
        id: 'r-kumano',
        name: '熊野古道',
        legs: [{ destinationId: 'kumano-kodo', days: 3 }],
        suitableThemes: ['sg', 'hs', 'wh', 'on', 'nt'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [3, 4],
        popularity: 4,
        titleSuffixes: ['熊野三山と世界遺産巡礼', '那智の滝と湯峯温泉', '熊野古道・大門坂歩き', '霊場と秘湯'],
    },
    {
        id: 'r-koyasan',
        name: '高野山',
        legs: [{ destinationId: 'koyasan', days: 2 }],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [2],
        popularity: 3,
        titleSuffixes: ['真言密教の聖地', '宿坊と奥之院', '世界遺産巡礼'],
    },
    {
        id: 'r-yoshino',
        name: '吉野山',
        legs: [{ destinationId: 'yoshino', days: 2 }],
        suitableThemes: ['np', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [2],
        seasonal: 'spring',
        titlePrefix: '春の',
        popularity: 3,
        titleSuffixes: ['千本桜と金峯山寺', '世界遺産桜の名所'],
    },
    {
        id: 'r-tottori',
        name: '鳥取砂丘・三朝',
        legs: [{ destinationId: 'tottori', days: 2 }],
        suitableThemes: ['np', 'on', 'ex'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['砂丘と砂の美術館', '三朝温泉と三徳山', '日本一の砂丘体験'],
    },
    {
        id: 'r-hagi-tsuwano',
        name: '萩・津和野',
        legs: [{ destinationId: 'hagi-tsuwano', days: 2 }],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪', '福岡'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['明治維新の城下町', '松陰神社と山陰の小京都', '世界遺産産業革命遺産'],
    },
    {
        id: 'r-kurobe',
        name: '黒部立山アルペンルート',
        legs: [{ destinationId: 'kurobe-tateyama', days: 3 }],
        suitableThemes: ['np', 'nt', 'ex', 'on'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [3, 4],
        popularity: 4,
        titleSuffixes: ['雪の大谷と黒部ダム', 'アルペンルート絶景縦断', '宇奈月トロッコ電車', '室堂と黒部峡谷'],
    },
    {
        id: 'r-zenkoji-nagano',
        name: '善光寺・長野',
        legs: [{ destinationId: 'zenkoji-nagano', days: 3 }],
        suitableThemes: ['sg', 'hs', 'on', 'gm', 'np'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [2, 3, 4],
        popularity: 4,
        titleSuffixes: ['善光寺と小布施', '地獄谷温泉と猿', '湯田中渋温泉巡り', '信州そばと温泉'],
    },
    {
        id: 'r-miura',
        name: '横須賀・三浦半島',
        legs: [{ destinationId: 'miura', days: 2 }],
        suitableThemes: ['sg', 'gm', 'np', 'cp'],
        suitableOrigins: ['大阪', '名古屋', '福岡'],
        durations: [1, 2],
        popularity: 2,
        titleSuffixes: ['三崎マグロと猿島', '東京近郊の海'],
    },
    {
        id: 'r-hamamatsu',
        name: '浜松・浜名湖',
        legs: [{ destinationId: 'hamamatsu', days: 2 }],
        suitableThemes: ['gm', 'on', 'fm', 'cp'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['うなぎと舘山寺温泉', '浜松城と浜名湖', 'うなぎパイファクトリー'],
    },
    {
        id: 'r-awaji',
        name: '淡路島',
        legs: [{ destinationId: 'awaji', days: 2 }],
        suitableThemes: ['np', 'fm', 'cp', 'gm', 'on'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [2, 3],
        popularity: 4,
        titleSuffixes: ['渦潮と淡路ハイウェイオアシス', 'おのころ島神社と温泉', '淡路ブランド食材巡り', '夢舞台と海の絶景'],
    },
    {
        id: 'r-shodoshima',
        name: '小豆島',
        legs: [{ destinationId: 'shodoshima', days: 2 }],
        suitableThemes: ['np', 'cp', 'gm', 'ar'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [2, 3],
        popularity: 3,
        titleSuffixes: ['エンジェルロードと寒霞渓', 'オリーブと醤油の島', '魔女宅の風車'],
    },

    // ──────────── 国内ニッチ＋既存の組み合わせ周遊 ────────────
    {
        id: 'r-kyoto-koyasan',
        name: '京都・高野山',
        legs: [
            { destinationId: 'kyoto', days: 2 },
            { destinationId: 'koyasan', days: 1 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '名古屋', '福岡'],
        durations: [3, 4],
        popularity: 3,
        titleSuffixes: ['古都と霊場', '京都と高野山', '世界遺産2か所'],
    },
    {
        id: 'r-kyoto-ise',
        name: '京都・伊勢神宮',
        legs: [
            { destinationId: 'kyoto', days: 2 },
            { destinationId: 'ise-shima', days: 2 },
        ],
        suitableThemes: ['sg', 'hs', 'gm'],
        suitableOrigins: ['東京', '名古屋', '福岡'],
        durations: [4, 5],
        popularity: 3,
        titleSuffixes: ['京都とお伊勢参り', '古都と伊勢神宮', '関西の神社仏閣'],
    },

    // ──────────── 南イタリア ────────────
    {
        id: 'r-south-italy',
        name: '南イタリア（ナポリ・カプリ・アマルフィ）',
        legs: [{ destinationId: 'south-italy', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np', 'cp', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 4,
        titleSuffixes: ['アマルフィ海岸と青の洞窟', 'ポンペイとカプリ島', '南イタリア絶景周遊', 'ナポリピザと地中海'],
    },
    {
        id: 'r-sicily',
        name: 'シチリア',
        legs: [{ destinationId: 'sicily', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7],
        popularity: 3,
        titleSuffixes: ['タオルミーナとエトナ山', 'シチリア島周遊', 'アグリジェント神殿の谷'],
    },
    {
        id: 'r-rome-south-italy',
        name: 'ローマ・南イタリア',
        legs: [
            { destinationId: 'rome', days: 3 },
            { destinationId: 'south-italy', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'wh', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 3,
        titleSuffixes: ['ローマと南イタリア', 'コロッセオとアマルフィ', 'イタリアハイライト南北'],
    },

    // ──────────── クロアチア ────────────
    {
        id: 'r-croatia',
        name: 'クロアチア（ドゥブロヴニク・プリトヴィツェ）',
        legs: [{ destinationId: 'croatia', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 4,
        titleSuffixes: ['アドリア海の真珠', 'ドゥブロヴニク城壁巡り', 'プリトヴィツェ16湖と滝', 'ゲームオブスローンズの舞台'],
    },
    {
        id: 'r-croatia-italy',
        name: 'クロアチア・イタリア',
        legs: [
            { destinationId: 'croatia', days: 3 },
            { destinationId: 'venice', days: 2 },
        ],
        suitableThemes: ['sg', 'hs', 'wh', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7],
        popularity: 2,
        titleSuffixes: ['アドリア海2か国', 'ドゥブロヴニク＋ベネチア'],
    },

    // ──────────── トルコ ────────────
    {
        id: 'r-turkey',
        name: 'トルコ周遊',
        legs: [{ destinationId: 'turkey', days: 6 }],
        suitableThemes: ['sg', 'hs', 'wh', 'ex', 'np', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 5,
        titleSuffixes: ['イスタンブール＋カッパドキア', '気球とアヤソフィア', 'パムッカレ石灰棚', 'シルクロードの十字路', '世界遺産トルコ周遊'],
    },

    // ──────────── ギリシャ ────────────
    {
        id: 'r-greece',
        name: 'ギリシャ（アテネ・サントリーニ）',
        legs: [{ destinationId: 'greece', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np', 'cp', 'bc'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 5,
        titleSuffixes: ['アクロポリスとサントリーニ', 'アテネとエーゲ海の島', '白と青の絶景', 'ハネムーンギリシャ', '古代神話の地'],
    },
    {
        id: 'r-greece-turkey',
        name: 'ギリシャ・トルコ',
        legs: [
            { destinationId: 'greece', days: 4 },
            { destinationId: 'turkey', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10],
        popularity: 2,
        titleSuffixes: ['エーゲ海2か国', '古代文明を辿る'],
    },

    // ──────────── スコットランド・アイルランド ────────────
    {
        id: 'r-scotland',
        name: 'スコットランド',
        legs: [{ destinationId: 'scotland', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['エディンバラとハイランド', 'ネス湖と城めぐり', 'ウイスキー蒸留所巡り', 'スカイ島絶景'],
    },
    {
        id: 'r-london-scotland',
        name: 'ロンドン・スコットランド',
        legs: [
            { destinationId: 'london', days: 3 },
            { destinationId: 'scotland', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8],
        popularity: 2,
        titleSuffixes: ['英国2大都市', 'ロンドンとエディンバラ', '英国列車旅'],
    },

    // ──────────── オーロラ専門 ────────────
    {
        id: 'r-rovaniemi',
        name: 'ロヴァニエミ（オーロラ）',
        legs: [{ destinationId: 'rovaniemi', days: 4 }],
        suitableThemes: ['np', 'cp', 'ex', 'fm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        seasonal: 'winter',
        titlePrefix: '冬の',
        popularity: 4,
        titleSuffixes: ['オーロラとサンタクロース村', 'ハスキー犬ぞりとサウナ', '北極圏アドベンチャー', 'ガラスイグルー宿泊'],
    },
    {
        id: 'r-iceland-aurora',
        name: 'アイスランド（オーロラ）',
        legs: [{ destinationId: 'reykjavik', days: 5 }],
        suitableThemes: ['np', 'cp', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7],
        seasonal: 'winter',
        titlePrefix: '冬の',
        popularity: 3,
        titleSuffixes: ['オーロラとブルーラグーン', 'ゴールデンサークル冬', '氷と火の島'],
    },

    // ──────────── 北米 詳細 ────────────
    {
        id: 'r-ny-boston-washington',
        name: 'NY・ボストン・ワシントン',
        legs: [
            { destinationId: 'newyork', days: 3 },
            { destinationId: 'boston-washington', days: 4 },
        ],
        suitableThemes: ['sg', 'hs', 'ar', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 3,
        titleSuffixes: ['アメリカ東海岸3都市', 'NY＋首都＋ハーバード', '東海岸ハイライト周遊'],
    },
    {
        id: 'r-boston-washington',
        name: 'ボストン・ワシントンDC',
        legs: [{ destinationId: 'boston-washington', days: 5 }],
        suitableThemes: ['sg', 'hs', 'ar'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 2,
        titleSuffixes: ['歴史と政治の中心', 'ハーバードとスミソニアン'],
    },
    {
        id: 'r-sf-la',
        name: 'サンフランシスコ・ロサンゼルス',
        legs: [
            { destinationId: 'sf', days: 3 },
            { destinationId: 'la', days: 3 },
        ],
        suitableThemes: ['sg', 'np', 'gm', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8],
        popularity: 4,
        titleSuffixes: ['西海岸2大都市', 'SFとハリウッド', 'カリフォルニアハイライト', '太平洋岸縦断'],
    },
    {
        id: 'r-sf-classic',
        name: 'サンフランシスコ',
        legs: [{ destinationId: 'sf', days: 4 }],
        suitableThemes: ['sg', 'gm', 'cp', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [4, 5, 6],
        popularity: 3,
        titleSuffixes: ['ゴールデンゲートとケーブルカー', 'アルカトラズとナパワイン', '坂の街SF王道'],
    },
    {
        id: 'r-grand-circle',
        name: 'グランドサークル',
        legs: [{ destinationId: 'grand-circle', days: 6 }],
        suitableThemes: ['np', 'nt', 'wh', 'sg'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9, 10],
        popularity: 4,
        titleSuffixes: ['グランドキャニオン＋セドナ', 'モニュメントバレーとアンテロープ', 'アメリカ大絶景縦断', 'ラスベガス起点国立公園'],
    },
    {
        id: 'r-grand-circle-la',
        name: 'ラスベガス・グランドキャニオン・LA',
        legs: [
            { destinationId: 'grand-circle', days: 4 },
            { destinationId: 'la', days: 3 },
        ],
        suitableThemes: ['np', 'sg', 'fm', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8],
        popularity: 3,
        titleSuffixes: ['西海岸＋グランドキャニオン', 'LA＋絶景国立公園'],
    },

    // ──────────── カナディアンロッキー ────────────
    {
        id: 'r-canadian-rockies',
        name: 'カナディアンロッキー',
        legs: [{ destinationId: 'canadian-rockies', days: 6 }],
        suitableThemes: ['np', 'nt', 'wh', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 4,
        titleSuffixes: ['バンフ・ジャスパー・ルイーズ湖', 'モレーン湖とコロンビア氷原', 'ロッキー山脈の宝石', 'ターコイズブルーの湖巡り'],
    },

    // ──────────── ハネムーン専用 ────────────
    {
        id: 'r-maldives',
        name: 'モルディブ',
        legs: [{ destinationId: 'maldives', days: 5 }],
        suitableThemes: ['bc', 'cp', 'on', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 5,
        titleSuffixes: ['ハネムーンモルディブ', '水上ヴィラで過ごす', '世界一の珊瑚礁とリゾート', 'インド洋の楽園', 'カップル極上時間'],
    },
    {
        id: 'r-bora-bora',
        name: 'タヒチ・ボラボラ',
        legs: [{ destinationId: 'bora-bora', days: 5 }],
        suitableThemes: ['bc', 'cp', 'on', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 4,
        titleSuffixes: ['ハネムーンボラボラ', '南太平洋の楽園', '水上ヴィラとオテマヌ', 'タヒチアンスパ満喫'],
    },
    {
        id: 'r-seychelles',
        name: 'セーシェル',
        legs: [{ destinationId: 'seychelles', days: 5 }],
        suitableThemes: ['bc', 'cp', 'np', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['ハネムーンセーシェル', '世界一美しいビーチ', 'マヘ＋プララン＋ラ・ディーグ', 'インド洋3島巡り'],
    },
    {
        id: 'r-bali-honeymoon',
        name: 'バリ ハネムーン',
        legs: [{ destinationId: 'bali', days: 5 }],
        suitableThemes: ['bc', 'cp', 'on'],
        suitableOrigins: ['東京', '大阪', '名古屋'],
        durations: [5, 6, 7],
        popularity: 4,
        titleSuffixes: ['ハネムーンバリ', 'ウブドとビーチリゾート', 'バリスパと夕日のディナー', '神々の島で2人時間'],
    },
    {
        id: 'r-hawaii-honeymoon',
        name: 'ハワイ ハネムーン',
        legs: [{ destinationId: 'hawaii-oahu', days: 5 }],
        suitableThemes: ['bc', 'cp', 'np'],
        suitableOrigins: ['東京', '大阪', '名古屋', '福岡'],
        durations: [5, 6, 7],
        popularity: 5,
        titleSuffixes: ['ハネムーンハワイ', 'ワイキキとカイルア', 'ハナウマ湾と夕日', 'ロマンチックハワイ', 'カップルで楽しむオアフ'],
    },
    {
        id: 'r-santorini-honeymoon',
        name: 'サントリーニ ハネムーン',
        legs: [{ destinationId: 'greece', days: 5 }],
        suitableThemes: ['cp', 'np', 'bc'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7],
        popularity: 3,
        titleSuffixes: ['ハネムーンサントリーニ', '白と青の島で2人時間', 'カルデラ夕日'],
    },
]
