import type { Route } from '../types'

// 海外追加 第4弾：アフリカ大幅拡充・中東・中央アジア（シルクロード）・南米追加

export const ROUTES_EXTRA_4: Route[] = [
    // ──────────── アフリカ ────────────
    {
        id: 'r-ethiopia',
        name: 'エチオピア',
        legs: [{ destinationId: 'ethiopia', days: 6 }],
        suitableThemes: ['sg', 'hs', 'wh', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9, 10],
        popularity: 2,
        titleSuffixes: ['ラリベラ岩窟教会群', 'アクスムとゴンダール', '世界遺産5箇所巡り', 'シミエン国立公園'],
    },
    {
        id: 'r-uganda-rwanda',
        name: 'ウガンダ・ルワンダ（ゴリラ）',
        legs: [{ destinationId: 'uganda-rwanda', days: 6 }],
        suitableThemes: ['nt', 'np', 'ex', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9, 10],
        popularity: 3,
        titleSuffixes: ['マウンテンゴリラトレッキング', 'ブウィンディとボルケーノ', 'ルワンダ＋ウガンダ縦断'],
    },
    {
        id: 'r-botswana',
        name: 'ボツワナ（オカバンゴ）',
        legs: [{ destinationId: 'botswana', days: 6 }],
        suitableThemes: ['nt', 'np', 'wh', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9, 10],
        popularity: 3,
        titleSuffixes: ['オカバンゴ・デルタ', 'チョベ国立公園と象', 'モコロ舟と動物', 'ボツワナラグジュアリーサファリ'],
    },
    {
        id: 'r-botswana-vicfalls',
        name: 'ボツワナ＋ヴィクトリアの滝',
        legs: [
            { destinationId: 'botswana', days: 4 },
            { destinationId: 'victoria-falls', days: 3 },
        ],
        suitableThemes: ['nt', 'np', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10, 11],
        popularity: 3,
        titleSuffixes: ['南部アフリカ大絶景', 'チョベ＋ヴィクトリアの滝', 'オカバンゴとザンベジ'],
    },
    {
        id: 'r-kilimanjaro',
        name: 'キリマンジャロ登山',
        legs: [{ destinationId: 'kilimanjaro', days: 7 }],
        suitableThemes: ['ex', 'np', 'nt', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [9, 10, 11],
        popularity: 2,
        titleSuffixes: ['アフリカ最高峰登頂', 'マチャメルート7日間', 'ウフルピーク挑戦'],
    },
    {
        id: 'r-kili-safari',
        name: 'キリマンジャロ登山＋サファリ',
        legs: [
            { destinationId: 'kilimanjaro', days: 6 },
            { destinationId: 'safari', days: 3 },
        ],
        suitableThemes: ['ex', 'np', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [10, 11, 12],
        popularity: 2,
        titleSuffixes: ['登頂とサファリの大冒険', '東アフリカ究極の旅'],
    },
    {
        id: 'r-tunisia',
        name: 'チュニジア',
        legs: [{ destinationId: 'tunisia', days: 6 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 2,
        titleSuffixes: ['カルタゴと青の街シディ・ブ・サイド', 'サハラ砂漠とローマ遺跡', 'チュニス＋ドゥッガ＋マトマタ', '北アフリカ世界遺産'],
    },
    {
        id: 'r-senegal',
        name: 'セネガル',
        legs: [{ destinationId: 'senegal', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 1,
        titleSuffixes: ['ゴレ島とサン＝ルイ', '西アフリカの世界遺産', 'ダカール＋ピンク湖'],
    },
    {
        id: 'r-ghana',
        name: 'ガーナ',
        legs: [{ destinationId: 'ghana', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 1,
        titleSuffixes: ['ケープコースト城と奴隷貿易史', 'カクム熱帯雨林とアクラ', '西アフリカ歴史紀行'],
    },

    // ──────────── 中東 ────────────
    {
        id: 'r-oman',
        name: 'オマーン',
        legs: [{ destinationId: 'oman', days: 6 }],
        suitableThemes: ['sg', 'np', 'nt', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 3,
        titleSuffixes: ['マスカットとワヒバ砂漠', 'ワディ・シャブとグランドモスク', 'アラビア半島の宝石', 'オマーン砂漠キャンプ'],
    },
    {
        id: 'r-saudi',
        name: 'サウジアラビア・アルウラ',
        legs: [{ destinationId: 'saudi', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 2,
        titleSuffixes: ['マダイン・サーレハと砂漠', 'アルウラ＋リヤド', 'もうひとつのペトラ'],
    },
    {
        id: 'r-lebanon',
        name: 'レバノン',
        legs: [{ destinationId: 'lebanon', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 2,
        titleSuffixes: ['バールベックとビブロス', 'メゼ料理と世界遺産', 'ベイルートと古代ローマ遺跡'],
    },
    {
        id: 'r-qatar',
        name: 'ドーハ・カタール',
        legs: [{ destinationId: 'qatar', days: 3 }],
        suitableThemes: ['sg', 'ar', 'sp', 'ng'],
        suitableOrigins: ['東京', '大阪'],
        durations: [3, 4, 5],
        popularity: 4,
        titleSuffixes: ['ストップオーバーで楽しむドーハ', 'イスラム美術館とスーク', 'モダンドーハ＋砂漠サファリ', '中東デザインの首都'],
    },
    {
        id: 'r-oman-qatar',
        name: 'オマーン＋カタール',
        legs: [
            { destinationId: 'oman', days: 4 },
            { destinationId: 'qatar', days: 2 },
        ],
        suitableThemes: ['sg', 'np', 'ar'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 2,
        titleSuffixes: ['アラビア半島2か国', 'マスカット＋ドーハ'],
    },

    // ──────────── 中央アジア・コーカサス ────────────
    {
        id: 'r-uzbekistan',
        name: 'ウズベキスタン（シルクロード）',
        legs: [{ destinationId: 'uzbekistan', days: 7 }],
        suitableThemes: ['sg', 'hs', 'wh', 'ar'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10],
        popularity: 3,
        titleSuffixes: ['サマルカンド＋ブハラ＋ヒヴァ', '青の世界遺産3都市', 'シルクロード周遊', 'レギスタン広場の青のタイル'],
    },
    {
        id: 'r-georgia',
        name: 'ジョージア（コーカサス）',
        legs: [{ destinationId: 'georgia', days: 6 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 3,
        titleSuffixes: ['トビリシとカズベギ', 'ワインとハチャプリ', 'ゲルゲティ三位一体教会', 'コーカサスハイライト'],
    },
    {
        id: 'r-uzbekistan-georgia',
        name: 'シルクロード＋コーカサス',
        legs: [
            { destinationId: 'uzbekistan', days: 5 },
            { destinationId: 'georgia', days: 4 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [10, 11, 12],
        popularity: 2,
        titleSuffixes: ['ウズベキスタン＋ジョージア', '青の都市とコーカサス'],
    },
    {
        id: 'r-iran',
        name: 'イラン',
        legs: [{ destinationId: 'iran', days: 7 }],
        suitableThemes: ['sg', 'hs', 'wh', 'ar'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10],
        popularity: 2,
        titleSuffixes: ['ペルセポリスとイスファハン', 'ピンクモスクと世界遺産', 'ペルシア文明大周遊', 'テヘラン＋イスファハン＋シーラーズ'],
    },

    // ──────────── 南米追加 ────────────
    {
        id: 'r-atacama',
        name: 'アタカマ砂漠（チリ）',
        legs: [{ destinationId: 'atacama', days: 5 }],
        suitableThemes: ['np', 'nt', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 2,
        titleSuffixes: ['月の谷と星空観賞', 'タティオ間欠泉とフラミンゴ', 'ALMA天文台と砂漠'],
    },
    {
        id: 'r-atacama-easter',
        name: 'アタカマ＋イースター島',
        legs: [
            { destinationId: 'atacama', days: 4 },
            { destinationId: 'easter-island', days: 3 },
        ],
        suitableThemes: ['np', 'sg', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [9, 10, 11],
        popularity: 2,
        titleSuffixes: ['チリ絶景2か所', '砂漠とモアイの神秘', 'チリ大周遊'],
    },
    {
        id: 'r-bogota',
        name: 'ボゴタ・コロンビア',
        legs: [{ destinationId: 'colombia-bogota', days: 4 }],
        suitableThemes: ['sg', 'gm', 'ar', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 2,
        titleSuffixes: ['ラ・カンデラリアと黄金博物館', '塩の大聖堂とモンセラーテ', 'コロンビアの首都体験'],
    },
    {
        id: 'r-colombia-grand',
        name: 'コロンビア大周遊（ボゴタ＋カルタヘナ）',
        legs: [
            { destinationId: 'colombia-bogota', days: 3 },
            { destinationId: 'cartagena', days: 4 },
        ],
        suitableThemes: ['sg', 'hs', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10],
        popularity: 2,
        titleSuffixes: ['コロンビアハイライト', 'ボゴタ＋カリブ世界遺産'],
    },
    {
        id: 'r-belize',
        name: 'ベリーズ',
        legs: [{ destinationId: 'belize', days: 5 }],
        suitableThemes: ['bc', 'nt', 'wh', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 2,
        titleSuffixes: ['グレートブルーホール体験', 'マヤ遺跡とカリブ海', 'キーカーカー＋カラコル', 'ベリーズ全制覇'],
    },
]
