import type { Route } from '../types'

// 海外を中心に大幅拡充：カナダ・中南米・インド南/聖地・アフリカ・北欧・中東

export const ROUTES_EXTRA_3: Route[] = [
    // ──────────── カナダ ────────────
    {
        id: 'r-toronto-niagara',
        name: 'トロント・ナイアガラ',
        legs: [{ destinationId: 'toronto-niagara', days: 4 }],
        suitableThemes: ['sg', 'np', 'fm', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [4, 5, 6],
        popularity: 4,
        titleSuffixes: ['ナイアガラの滝とCNタワー', 'カナダ東部ハイライト', 'ナイアガラクルーズ体験'],
    },
    {
        id: 'r-montreal-quebec',
        name: 'モントリオール・ケベック',
        legs: [{ destinationId: 'montreal-quebec', days: 4 }],
        suitableThemes: ['sg', 'hs', 'wh', 'gm', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6],
        popularity: 3,
        titleSuffixes: ['フレンチカナダ周遊', 'ケベック旧市街と城下町', 'モントリオール＋世界遺産'],
    },
    {
        id: 'r-canada-east',
        name: 'カナダ東部周遊（トロント・モントリオール・ケベック）',
        legs: [
            { destinationId: 'toronto-niagara', days: 3 },
            { destinationId: 'montreal-quebec', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 4,
        titleSuffixes: ['東カナダ大周遊', 'トロント＋ナイアガラ＋ケベック', 'カナダ世界遺産巡り', 'メープル街道'],
    },
    {
        id: 'r-pei',
        name: 'プリンスエドワード島',
        legs: [{ destinationId: 'pei', days: 3 }],
        suitableThemes: ['sg', 'cp', 'np', 'fm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [3, 4, 5],
        popularity: 3,
        titleSuffixes: ['赤毛のアンの島へ', 'グリーン・ゲイブルズ巡礼', 'カナダ大西洋岸'],
    },
    {
        id: 'r-canada-east-pei',
        name: '東カナダ＋赤毛のアン（モントリオール・ケベック・PEI）',
        legs: [
            { destinationId: 'montreal-quebec', days: 3 },
            { destinationId: 'pei', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8],
        popularity: 2,
        titleSuffixes: ['東カナダ周遊＋赤毛のアン'],
    },

    // ──────────── ブラジル ────────────
    {
        id: 'r-rio',
        name: 'リオデジャネイロ',
        legs: [{ destinationId: 'rio', days: 4 }],
        suitableThemes: ['np', 'bc', 'sg', 'cp', 'ng'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 4,
        titleSuffixes: ['キリスト像とコパカバーナ', 'カーニバルの街', 'リオの絶景3名所'],
    },
    {
        id: 'r-iguazu',
        name: 'イグアスの滝',
        legs: [{ destinationId: 'iguazu', days: 3 }],
        suitableThemes: ['np', 'wh', 'nt', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [4, 5],
        popularity: 3,
        titleSuffixes: ['ブラジル＋アルゼンチン両側', '世界三大瀑布', 'マクコサファリ'],
    },
    {
        id: 'r-brazil-grand',
        name: 'ブラジル周遊（リオ・イグアス・サンパウロ）',
        legs: [
            { destinationId: 'rio', days: 3 },
            { destinationId: 'iguazu', days: 2 },
        ],
        suitableThemes: ['np', 'sg', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 5,
        titleSuffixes: ['リオ＋イグアス周遊', 'ブラジル絶景ハイライト', '南米2大ハイライト', 'サンバとイグアス'],
    },
    {
        id: 'r-amazon',
        name: 'アマゾン',
        legs: [{ destinationId: 'amazon', days: 4 }],
        suitableThemes: ['nt', 'np', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 2,
        titleSuffixes: ['アマゾン河とジャングル', 'ピンクイルカと熱帯雨林'],
    },

    // ──────────── アルゼンチン ────────────
    {
        id: 'r-buenos-aires',
        name: 'ブエノスアイレス',
        legs: [{ destinationId: 'buenos-aires', days: 4 }],
        suitableThemes: ['sg', 'gm', 'ar', 'ng'],
        suitableOrigins: ['東京', '大阪'],
        durations: [4, 5, 6],
        popularity: 3,
        titleSuffixes: ['タンゴとステーキ', 'アルゼンチン首都ハイライト', '南米のパリ'],
    },
    {
        id: 'r-patagonia',
        name: 'パタゴニア',
        legs: [{ destinationId: 'patagonia', days: 5 }],
        suitableThemes: ['np', 'nt', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9, 10],
        popularity: 3,
        titleSuffixes: ['ペリト・モレノ氷河', 'トーレス・デル・パイネ', 'フィッツロイ展望', '世界の果ての絶景'],
    },
    {
        id: 'r-argentina-chile',
        name: 'アルゼンチン＋チリ周遊',
        legs: [
            { destinationId: 'buenos-aires', days: 3 },
            { destinationId: 'patagonia', days: 4 },
        ],
        suitableThemes: ['sg', 'np', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10, 11],
        popularity: 3,
        titleSuffixes: ['南米2か国大周遊', 'ブエノスアイレス＋パタゴニア', '都市とパタゴニア氷河'],
    },
    {
        id: 'r-easter-island',
        name: 'イースター島',
        legs: [{ destinationId: 'easter-island', days: 4 }],
        suitableThemes: ['sg', 'hs', 'wh', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 2,
        titleSuffixes: ['モアイ像と神秘の島', '世界一遠い島へ'],
    },

    // ──────────── コスタリカ・コロンビア ────────────
    {
        id: 'r-costa-rica',
        name: 'コスタリカ',
        legs: [{ destinationId: 'costa-rica', days: 5 }],
        suitableThemes: ['nt', 'ex', 'np', 'bc'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['火山＋雲霧林＋ビーチ', 'エコツーリズム王道', 'アレナルとモンテベルデ'],
    },
    {
        id: 'r-cartagena',
        name: 'カルタヘナ・コロンビア',
        legs: [{ destinationId: 'cartagena', days: 4 }],
        suitableThemes: ['sg', 'hs', 'wh', 'cp', 'bc'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 2,
        titleSuffixes: ['カリブの世界遺産旧市街', 'ロサリオ諸島とカルタヘナ'],
    },

    // ──────────── インド南/聖地 ────────────
    {
        id: 'r-kerala',
        name: 'ケララ・南インド',
        legs: [{ destinationId: 'kerala', days: 5 }],
        suitableThemes: ['np', 'on', 'cp', 'nt', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['バックウォーターとアーユルヴェーダ', '南インド楽園', 'ハウスボートとムンナール'],
    },
    {
        id: 'r-varanasi',
        name: 'バラナシ・ガンジス川',
        legs: [{ destinationId: 'varanasi', days: 3 }],
        suitableThemes: ['sg', 'hs'],
        suitableOrigins: ['東京', '大阪'],
        durations: [4, 5],
        popularity: 3,
        titleSuffixes: ['ガンジス川の聖地', '早朝の沐浴とアールティ', 'インド聖地巡礼'],
    },
    {
        id: 'r-india-deep',
        name: 'インド大周遊（ゴールデントライアングル＋バラナシ）',
        legs: [
            { destinationId: 'india-golden', days: 4 },
            { destinationId: 'varanasi', days: 2 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 4,
        titleSuffixes: ['インド大周遊', 'タージマハル＋ガンジス川', '北インド全制覇', 'ムガル帝国＋聖地巡礼'],
    },

    // ──────────── アフリカ ────────────
    {
        id: 'r-tanzania-zanzibar',
        name: 'タンザニア・ザンジバル',
        legs: [{ destinationId: 'tanzania-zanzibar', days: 6 }],
        suitableThemes: ['nt', 'np', 'wh', 'ex', 'bc'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9, 10],
        popularity: 4,
        titleSuffixes: ['セレンゲティとザンジバル', 'サファリ＋インド洋ビーチ', 'ンゴロンゴロとビーチ', 'タンザニア全制覇'],
    },
    {
        id: 'r-kenya-tanzania-grand',
        name: '東アフリカ大周遊（ケニア＋タンザニア＋ザンジバル）',
        legs: [
            { destinationId: 'safari', days: 4 },
            { destinationId: 'tanzania-zanzibar', days: 4 },
        ],
        suitableThemes: ['nt', 'np', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [9, 10, 11, 12],
        popularity: 3,
        titleSuffixes: ['東アフリカ大サファリ', 'ケニア＋タンザニア＋ザンジバル', 'ビッグ5とインド洋'],
    },
    {
        id: 'r-madagascar',
        name: 'マダガスカル',
        legs: [{ destinationId: 'madagascar', days: 5 }],
        suitableThemes: ['nt', 'np', 'ex'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8, 9],
        popularity: 2,
        titleSuffixes: ['バオバブ街道とキツネザル', '世界遺産ツィンギ', '進化の島'],
    },
    {
        id: 'r-victoria-falls',
        name: 'ヴィクトリアの滝',
        legs: [{ destinationId: 'victoria-falls', days: 4 }],
        suitableThemes: ['np', 'wh', 'ex', 'nt'],
        suitableOrigins: ['東京', '大阪'],
        durations: [5, 6, 7],
        popularity: 3,
        titleSuffixes: ['世界三大瀑布', 'デビルズプール体験', 'ザンベジ川クルーズ', 'チョベ国立公園'],
    },
    {
        id: 'r-vic-falls-safari',
        name: 'ヴィクトリアの滝＋ケニアサファリ',
        legs: [
            { destinationId: 'victoria-falls', days: 3 },
            { destinationId: 'safari', days: 4 },
        ],
        suitableThemes: ['np', 'nt', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10],
        popularity: 3,
        titleSuffixes: ['南北アフリカ絶景縦断', '滝とサファリ', 'アフリカハイライト'],
    },
    {
        id: 'r-mauritius',
        name: 'モーリシャス',
        legs: [{ destinationId: 'mauritius', days: 5 }],
        suitableThemes: ['bc', 'cp', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['インド洋ハネムーン', 'ル・モーンと7色の大地', 'モーリシャスリゾート'],
    },

    // ──────────── 中東 ────────────
    {
        id: 'r-israel',
        name: 'イスラエル',
        legs: [{ destinationId: 'israel', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['エルサレム3宗教聖地', '死海とマサダ', 'テルアビブとベツレヘム', '聖地巡礼'],
    },
    {
        id: 'r-israel-jordan',
        name: 'イスラエル・ヨルダン',
        legs: [
            { destinationId: 'israel', days: 4 },
            { destinationId: 'jordan', days: 4 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [8, 9, 10],
        popularity: 3,
        titleSuffixes: ['中東聖地2か国', 'エルサレム＋ペトラ', '聖書世界ハイライト'],
    },

    // ──────────── ヨーロッパ追加 ────────────
    {
        id: 'r-norway-fjord',
        name: 'ノルウェー・フィヨルド',
        legs: [{ destinationId: 'norway-fjord', days: 5 }],
        suitableThemes: ['np', 'nt', 'wh', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['フィヨルド絶景巡り', 'ベルゲンとフロム鉄道', 'ガイランゲルとソグネ', '世界遺産フィヨルド'],
    },
    {
        id: 'r-ireland',
        name: 'アイルランド',
        legs: [{ destinationId: 'ireland', days: 5 }],
        suitableThemes: ['sg', 'hs', 'np', 'gm'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 3,
        titleSuffixes: ['ダブリンとモハーの断崖', 'ギネスとケルト文化', 'ジャイアンツ・コーズウェー'],
    },
    {
        id: 'r-uk-ireland',
        name: 'イギリス・アイルランド',
        legs: [
            { destinationId: 'london', days: 3 },
            { destinationId: 'ireland', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'np'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8],
        popularity: 3,
        titleSuffixes: ['英愛2か国', 'ロンドン＋ダブリン', 'ケルト文化と王室'],
    },
    {
        id: 'r-poland',
        name: 'ポーランド',
        legs: [{ destinationId: 'poland', days: 5 }],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 2,
        titleSuffixes: ['クラクフ＋ワルシャワ', 'アウシュビッツと歴史', '中欧世界遺産'],
    },
    {
        id: 'r-poland-central-eu',
        name: 'ポーランド＋中欧',
        legs: [
            { destinationId: 'poland', days: 3 },
            { destinationId: 'prague', days: 3 },
        ],
        suitableThemes: ['sg', 'hs', 'wh'],
        suitableOrigins: ['東京', '大阪'],
        durations: [7, 8],
        popularity: 2,
        titleSuffixes: ['ポーランド＋プラハ', '中欧歴史巡り'],
    },

    // ──────────── モンゴル ────────────
    {
        id: 'r-mongolia',
        name: 'モンゴル',
        legs: [{ destinationId: 'mongolia', days: 5 }],
        suitableThemes: ['nt', 'np', 'ex', 'cp'],
        suitableOrigins: ['東京', '大阪'],
        durations: [6, 7, 8],
        popularity: 2,
        titleSuffixes: ['草原と遊牧民', 'ゲル宿泊とゴビ砂漠', 'チンギスハーンの大地'],
    },
]
